-- Auto-generated verified Quran surah seed SQL
-- Generated by tool/generate_quran_surah_seed.dart
-- Source docs: https://api-docs.quran.com/docs/content_apis_versioned/list-chapters/
-- Source API EN: https://api.quran.com/api/v4/chapters?language=en
-- Source API TR: https://api.quran.com/api/v4/chapters?language=tr
-- Verified at: 2026-04-08T13:14:13.578198Z

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  1, 'الفاتحة', 'Fâtiha', 'The Opener', 'Al-Fatihah', 7, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  2, 'البقرة', 'Bakara', 'The Cow', 'Al-Baqarah', 286, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  3, 'آل عمران', 'Âl-i İmrân', 'Family of Imran', 'Ali ''Imran', 200, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  4, 'النساء', 'Nisâ', 'The Women', 'An-Nisa', 176, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  5, 'المائدة', 'Mâide', 'The Table Spread', 'Al-Ma''idah', 120, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  6, 'الأنعام', 'En''âm', 'The Cattle', 'Al-An''am', 165, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  7, 'الأعراف', 'A''râf', 'The Heights', 'Al-A''raf', 206, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  8, 'الأنفال', 'Enfâl', 'The Spoils of War', 'Al-Anfal', 75, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  9, 'التوبة', 'Tevbe', 'The Repentance', 'At-Tawbah', 129, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  10, 'يونس', 'Yûnus', 'Jonah', 'Yunus', 109, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  11, 'هود', 'Hûd', 'Hud', 'Hud', 123, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  12, 'يوسف', 'Yûsuf', 'Joseph', 'Yusuf', 111, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  13, 'الرعد', 'Ra''d', 'The Thunder', 'Ar-Ra''d', 43, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  14, 'ابراهيم', 'İbrâhîm', 'Abraham', 'Ibrahim', 52, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  15, 'الحجر', 'Hicr', 'The Rocky Tract', 'Al-Hijr', 99, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  16, 'النحل', 'Nahl', 'The Bee', 'An-Nahl', 128, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  17, 'الإسراء', 'İsrâ', 'The Night Journey', 'Al-Isra', 111, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  18, 'الكهف', 'Kehf', 'The Cave', 'Al-Kahf', 110, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  19, 'مريم', 'Meryem', 'Mary', 'Maryam', 98, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  20, 'طه', 'Tâhâ', 'Ta-Ha', 'Taha', 135, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  21, 'الأنبياء', 'Enbiyâ', 'The Prophets', 'Al-Anbya', 112, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  22, 'الحج', 'Hac', 'The Pilgrimage', 'Al-Hajj', 78, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  23, 'المؤمنون', 'Mü''minûn', 'The Believers', 'Al-Mu''minun', 118, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  24, 'النور', 'Nûr', 'The Light', 'An-Nur', 64, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  25, 'الفرقان', 'Furkân', 'The Criterion', 'Al-Furqan', 77, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  26, 'الشعراء', 'Şuarâ', 'The Poets', 'Ash-Shu''ara', 227, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  27, 'النمل', 'Neml', 'The Ant', 'An-Naml', 93, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  28, 'القصص', 'Kasas', 'The Stories', 'Al-Qasas', 88, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  29, 'العنكبوت', 'Ankebût', 'The Spider', 'Al-''Ankabut', 69, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  30, 'الروم', 'Rûm', 'The Romans', 'Ar-Rum', 60, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  31, 'لقمان', 'Lokmân', 'Luqman', 'Luqman', 34, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  32, 'السجدة', 'Secde', 'The Prostration', 'As-Sajdah', 30, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  33, 'الأحزاب', 'Ahzâb', 'The Combined Forces', 'Al-Ahzab', 73, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  34, 'سبإ', 'Sebe''', 'Sheba', 'Saba', 54, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  35, 'فاطر', 'Fâtır', 'Originator', 'Fatir', 45, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  36, 'يس', 'Yâsîn', 'Ya Sin', 'Ya-Sin', 83, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  37, 'الصافات', 'Sâffât', 'Those who set the Ranks', 'As-Saffat', 182, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  38, 'ص', 'Sâd', 'The Letter "Saad"', 'Sad', 88, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  39, 'الزمر', 'Zümer', 'The Troops', 'Az-Zumar', 75, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  40, 'غافر', 'Mü''min', 'The Forgiver', 'Ghafir', 85, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  41, 'فصلت', 'Fussilet', 'Explained in Detail', 'Fussilat', 54, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  42, 'الشورى', 'Şûrâ', 'The Consultation', 'Ash-Shuraa', 53, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  43, 'الزخرف', 'Zuhruf', 'The Ornaments of Gold', 'Az-Zukhruf', 89, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  44, 'الدخان', 'Duhân', 'The Smoke', 'Ad-Dukhan', 59, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  45, 'الجاثية', 'Câsiye', 'The Crouching', 'Al-Jathiyah', 37, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  46, 'الأحقاف', 'Ahkâf', 'The Wind-Curved Sandhills', 'Al-Ahqaf', 35, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  47, 'محمد', 'Muhammed', 'Muhammad', 'Muhammad', 38, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  48, 'الفتح', 'Fetih', 'The Victory', 'Al-Fath', 29, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  49, 'الحجرات', 'Hucurât', 'The Rooms', 'Al-Hujurat', 18, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  50, 'ق', 'Kâf', 'The Letter "Qaf"', 'Qaf', 45, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  51, 'الذاريات', 'Zâriyât', 'The Winnowing Winds', 'Adh-Dhariyat', 60, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  52, 'الطور', 'Tûr', 'The Mount', 'At-Tur', 49, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  53, 'النجم', 'Necm', 'The Star', 'An-Najm', 62, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  54, 'القمر', 'Kamer', 'The Moon', 'Al-Qamar', 55, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  55, 'الرحمن', 'Rahmân', 'The Beneficent', 'Ar-Rahman', 78, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  56, 'الواقعة', 'Vâkıa', 'The Inevitable', 'Al-Waqi''ah', 96, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  57, 'الحديد', 'Hadîd', 'The Iron', 'Al-Hadid', 29, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  58, 'المجادلة', 'Mücâdele', 'The Pleading Woman', 'Al-Mujadila', 22, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  59, 'الحشر', 'Haşr', 'The Exile', 'Al-Hashr', 24, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  60, 'الممتحنة', 'Mümtehine', 'She that is to be examined', 'Al-Mumtahanah', 13, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  61, 'الصف', 'Saf', 'The Ranks', 'As-Saf', 14, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  62, 'الجمعة', 'Cuma', 'The Congregation, Friday', 'Al-Jumu''ah', 11, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  63, 'المنافقون', 'Münâfikûn', 'The Hypocrites', 'Al-Munafiqun', 11, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  64, 'التغابن', 'Tegâbün', 'The Mutual Disillusion', 'At-Taghabun', 18, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  65, 'الطلاق', 'Talâk', 'The Divorce', 'At-Talaq', 12, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  66, 'التحريم', 'Tahrîm', 'The Prohibition', 'At-Tahrim', 12, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  67, 'الملك', 'Mülk', 'The Sovereignty', 'Al-Mulk', 30, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  68, 'القلم', 'Kalem', 'The Pen', 'Al-Qalam', 52, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  69, 'الحاقة', 'Hâkka', 'The Reality', 'Al-Haqqah', 52, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  70, 'المعارج', 'Meâric', 'The Ascending Stairways', 'Al-Ma''arij', 44, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  71, 'نوح', 'Nûh', 'Noah', 'Nuh', 28, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  72, 'الجن', 'Cin', 'The Jinn', 'Al-Jinn', 28, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  73, 'المزمل', 'Müzzemmil', 'The Enshrouded One', 'Al-Muzzammil', 20, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  74, 'المدثر', 'Müddessir', 'The Cloaked One', 'Al-Muddaththir', 56, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  75, 'القيامة', 'Kıyâmet', 'The Resurrection', 'Al-Qiyamah', 40, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  76, 'الانسان', 'İnsân', 'The Man', 'Al-Insan', 31, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  77, 'المرسلات', 'Mürselât', 'The Emissaries', 'Al-Mursalat', 50, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  78, 'النبإ', 'Nebe', 'The Tidings', 'An-Naba', 40, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  79, 'النازعات', 'Naziât', 'Those who drag forth', 'An-Nazi''at', 46, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  80, 'عبس', 'Abese', 'He Frowned', '''Abasa', 42, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  81, 'التكوير', 'Tekvîr', 'The Overthrowing', 'At-Takwir', 29, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  82, 'الإنفطار', 'İnfitâr', 'The Cleaving', 'Al-Infitar', 19, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  83, 'المطففين', 'Mutaffifîn', 'The Defrauding', 'Al-Mutaffifin', 36, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  84, 'الإنشقاق', 'İnşikâk', 'The Sundering', 'Al-Inshiqaq', 25, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  85, 'البروج', 'Burûc', 'The Mansions of the Stars', 'Al-Buruj', 22, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  86, 'الطارق', 'Târık', 'The Nightcommer', 'At-Tariq', 17, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  87, 'الأعلى', 'A''lâ', 'The Most High', 'Al-A''la', 19, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  88, 'الغاشية', 'Gâşiye', 'The Overwhelming', 'Al-Ghashiyah', 26, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  89, 'الفجر', 'Fecr', 'The Dawn', 'Al-Fajr', 30, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  90, 'البلد', 'Beled', 'The City', 'Al-Balad', 20, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  91, 'الشمس', 'Şems', 'The Sun', 'Ash-Shams', 15, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  92, 'الليل', 'Leyl', 'The Night', 'Al-Layl', 21, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  93, 'الضحى', 'Duhâ', 'The Morning Hours', 'Ad-Duhaa', 11, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  94, 'الشرح', 'İnşirâh', 'The Relief', 'Ash-Sharh', 8, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  95, 'التين', 'Tîn', 'The Fig', 'At-Tin', 8, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  96, 'العلق', 'Alak', 'The Clot', 'Al-''Alaq', 19, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  97, 'القدر', 'Kadir', 'The Power', 'Al-Qadr', 5, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  98, 'البينة', 'Beyyine', 'The Clear Proof', 'Al-Bayyinah', 8, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  99, 'الزلزلة', 'Zilzâl', 'The Earthquake', 'Az-Zalzalah', 8, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  100, 'العاديات', 'Âdiyât', 'The Courser', 'Al-''Adiyat', 11, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  101, 'القارعة', 'Kâria', 'The Calamity', 'Al-Qari''ah', 11, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  102, 'التكاثر', 'Tekâsür', 'The Rivalry in world increase', 'At-Takathur', 8, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  103, 'العصر', 'Asr', 'The Declining Day', 'Al-''Asr', 3, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  104, 'الهمزة', 'Hümeze', 'The Traducer', 'Al-Humazah', 9, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  105, 'الفيل', 'Fîl', 'The Elephant', 'Al-Fil', 5, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  106, 'قريش', 'Kureyş', 'Quraysh', 'Quraysh', 4, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  107, 'الماعون', 'Maûn', 'The Small kindnesses', 'Al-Ma''un', 7, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  108, 'الكوثر', 'Kevser', 'The Abundance', 'Al-Kawthar', 3, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  109, 'الكافرون', 'Kâfirûn', 'The Disbelievers', 'Al-Kafirun', 6, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  110, 'النصر', 'Nasr', 'The Divine Support', 'An-Nasr', 3, 'Medinan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  111, 'المسد', 'Tebbet', 'The Palm Fiber', 'Al-Masad', 5, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  112, 'الإخلاص', 'İhlâs', 'The Sincerity', 'Al-Ikhlas', 4, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  113, 'الفلق', 'Felak', 'The Daybreak', 'Al-Falaq', 5, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.quran_surahs (
  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at
) VALUES (
  114, 'الناس', 'Nâs', 'Mankind', 'An-Nas', 6, 'Meccan', 'https://api.quran.com/api/v4/chapters', TIMESTAMPTZ '2026-04-08T13:14:13.578198Z'
) ON CONFLICT (surah_number) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  name_transliteration = EXCLUDED.name_transliteration,
  ayah_count = EXCLUDED.ayah_count,
  revelation_type = EXCLUDED.revelation_type,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

