-- Verified education content seed SQL.
-- Apply content_schema.sql before this seed.
-- Rows replace legacy placeholder education copy with concise sourced content.

INSERT INTO public.education_categories (
  id, title, title_en, icon, description, description_en, sort_order, source, verified_at
) VALUES
  ($$iman$$, $$İman Esasları$$, $$Articles of Faith$$, $$🕋$$, $$İslam inancının temel esasları.$$,
   $$Core foundations of Islamic belief.$$, 1, $$https://islamansiklopedisi.org.tr/iman$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$islam$$, $$İslam'ın Şartları$$, $$Pillars of Islam$$, $$☪️$$, $$Müslümanın temel ibadet ve kulluk başlıkları.$$,
   $$Foundational acts of worship and devotion.$$, 2, $$https://islamansiklopedisi.org.tr/islam$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$seerah$$, $$Siyer$$, $$Prophetic Biography$$, $$🌙$$, $$Hz. Muhammed'in (s.a.v.) hayatından güvenilir başlıklar.$$,
   $$Reliable themes from the Prophet Muhammad's life.$$, 3, $$https://islamansiklopedisi.org.tr/muhammed$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$fiqh$$, $$Fıkıh ve İbadet$$, $$Fiqh and Worship$$, $$📘$$, $$Günlük ibadetlerde temel ilmihal bilgileri.$$,
   $$Essential catechism guidance for daily worship.$$, 4, $$https://islamansiklopedisi.org.tr/fikih$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$ahlak$$, $$Ahlak ve Adab$$, $$Ethics and Adab$$, $$🤲$$, $$Kur'an ve sünnetin öğrettiği ahlaki ilkeler.$$,
   $$Ethical principles taught by the Quran and Sunnah.$$, 5, $$https://islamansiklopedisi.org.tr/ahlak$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$history$$, $$İslam Tarihi$$, $$Islamic History$$, $$🏛️$$, $$İslam tarihinin ana dönemleri ve medeniyet mirası.$$,
   $$Major periods and civilizational heritage of Islamic history.$$, 6, $$https://islamansiklopedisi.org.tr/islam-tarihi$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$mesajlar$$, $$Ayet ve Hadis Rehberi$$, $$Quran and Hadith Guide$$, $$📖$$, $$Ayet ve hadisleri kaynak bilinciyle okuma rehberi.$$,
   $$A source-aware guide for reading Quran and hadith.$$, 7, $$https://quran.com$$, TIMESTAMPTZ '2026-04-23T00:00:00Z')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  icon = EXCLUDED.icon,
  description = EXCLUDED.description,
  description_en = EXCLUDED.description_en,
  sort_order = EXCLUDED.sort_order,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;

INSERT INTO public.education_topics (
  id, category_id, title, title_en, content, content_en, sort_order, source, verified_at
) VALUES
  ($$iman_1$$, $$iman$$, $$Allah'a İman$$, $$Belief in Allah$$,
   $$Allah'a iman, O'nun birliğini, yaratıcı ve hüküm sahibi olduğunu kabul etmektir. Bu inanç ibadetin yalnız Allah'a yöneltilmesini gerektirir.$$,
   $$Belief in Allah means affirming His oneness, creation, and authority. Worship is directed to Allah alone.$$, 1, $$https://islamansiklopedisi.org.tr/iman$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$iman_2$$, $$iman$$, $$Meleklere İman$$, $$Belief in Angels$$,
   $$Melekler Allah'ın emirlerini yerine getiren gayb varlıklarıdır. Mümin, Kur'an ve sahih haberlerde bildirilen meleklere iman eder.$$,
   $$Angels are unseen servants who carry out Allah's commands. Muslims affirm what the Quran and sound reports teach about them.$$, 2, $$https://islamansiklopedisi.org.tr/melek$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$iman_3$$, $$iman$$, $$Kitaplara İman$$, $$Belief in Divine Books$$,
   $$Mümin, Allah'ın peygamberlerine vahiy gönderdiğine inanır. Kur'an-ı Kerim Müslümanlar için son ilahi kitaptır.$$,
   $$Muslims believe Allah sent revelation to His messengers. The Quran is the final divine book for Muslims.$$, 3, $$https://islamansiklopedisi.org.tr/kitap$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$iman_4$$, $$iman$$, $$Peygamberlere İman$$, $$Belief in Prophets$$,
   $$Peygamberler Allah'ın mesajını insanlara ulaştıran seçilmiş kullardır. Mümin peygamberler arasında iman bakımından ayrım yapmaz.$$,
   $$Prophets are chosen servants who conveyed Allah's message. Muslims affirm the prophets without rejecting any of them.$$, 4, $$https://islamansiklopedisi.org.tr/peygamber$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$iman_5$$, $$iman$$, $$Ahirete İman$$, $$Belief in the Hereafter$$,
   $$Ahirete iman; ölümden sonra diriliş, hesap ve Allah'ın adaletiyle karşılık görme inancını içerir.$$,
   $$Belief in the Hereafter includes resurrection, accountability, and recompense through Allah's justice.$$, 5, $$https://islamansiklopedisi.org.tr/ahiret$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$iman_6$$, $$iman$$, $$Kadere İman$$, $$Belief in Qadar$$,
   $$Kadere iman, Allah'ın ilminin her şeyi kuşattığını ve insanın sorumluluk bilinciyle amel etmesi gerektiğini öğretir.$$,
   $$Belief in qadar teaches that Allah's knowledge encompasses all things while people remain responsible for their choices.$$, 6, $$https://islamansiklopedisi.org.tr/kader$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),

  ($$shahada$$, $$islam$$, $$Şehadet$$, $$Testimony of Faith$$,
   $$Şehadet, Allah'tan başka ilah olmadığına ve Hz. Muhammed'in Allah'ın elçisi olduğuna imanla tanıklık etmektir.$$,
   $$The testimony affirms that there is no deity but Allah and that Muhammad is Allah's messenger.$$, 1, $$https://islamansiklopedisi.org.tr/sehadet$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$salat$$, $$islam$$, $$Namaz$$, $$Prayer$$,
   $$Namaz, vakitleri belirlenmiş farz ibadettir. Temizlik, kıble, niyet ve huşu gibi şart ve adabına özen gösterilir.$$,
   $$Prayer is an obligatory act of worship at appointed times. Purity, qibla, intention, and reverence are observed.$$, 2, $$https://islamansiklopedisi.org.tr/namaz$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$sawm$$, $$islam$$, $$Oruç$$, $$Fasting$$,
   $$Ramazan orucu, imsak ile iftar arasında yeme, içme ve orucu bozan davranışlardan uzak durarak tutulur.$$,
   $$Ramadan fasting is observed from dawn to sunset by abstaining from food, drink, and actions that invalidate the fast.$$, 3, $$https://islamansiklopedisi.org.tr/oruc$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$zakat$$, $$islam$$, $$Zekat$$, $$Zakat$$,
   $$Zekat, şartlarını taşıyan mallardan ihtiyaç sahiplerine verilen farz mali ibadettir. Nisap ve mal türü ilmihal hükümlerine göre değerlendirilir.$$,
   $$Zakat is an obligatory financial worship paid from qualifying wealth to eligible recipients; nisab and asset rules are assessed through fiqh.$$, 4, $$https://islamansiklopedisi.org.tr/zekat$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$hajj$$, $$islam$$, $$Hac$$, $$Hajj$$,
   $$Hac, gücü yeten Müslümanların belirli zamanda Kabe ve çevresindeki menasiki yerine getirmesidir.$$,
   $$Hajj is the pilgrimage performed by able Muslims at its appointed time through the prescribed rites around the Kaaba.$$, 5, $$https://islamansiklopedisi.org.tr/hac$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),

  ($$seerah_1$$, $$seerah$$, $$Hz. Muhammed'in Doğumu$$, $$Birth of Prophet Muhammad$$,
   $$Hz. Muhammed (s.a.v.) Mekke'de doğdu; güvenilirliği ve güzel ahlakı risaletinden önce de toplumunda biliniyordu.$$,
   $$Prophet Muhammad was born in Mecca; his trustworthiness and noble character were known before prophethood.$$, 1, $$https://islamansiklopedisi.org.tr/muhammed$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$seerah_2$$, $$seerah$$, $$İlk Vahiy$$, $$First Revelation$$,
   $$İlk vahiy Hira'da başladı. Vahiy süreci Kur'an'ın insanlığa hidayet olarak indirilmesinin başlangıcıdır.$$,
   $$The first revelation began in Hira and marks the beginning of the Quran's guidance for humanity.$$, 2, $$https://islamansiklopedisi.org.tr/vahiy$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$seerah_3$$, $$seerah$$, $$Veda Haccı$$, $$Farewell Pilgrimage$$,
   $$Veda Haccı, Hz. Peygamber'in ümmete temel haklar, emanet bilinci ve takva vurgusu yaptığı son büyük hacdır.$$,
   $$The Farewell Pilgrimage emphasized rights, trust, and God-consciousness in the Prophet's final major pilgrimage.$$, 3, $$https://islamansiklopedisi.org.tr/veda-hacci$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),

  ($$fiqh_1$$, $$fiqh$$, $$Abdest$$, $$Ablution$$,
   $$Abdest, namaz gibi ibadetler öncesinde yapılan hükmi temizliktir. Farz ve sünnetleri mezhep ilmihallerinde ayrıntılı açıklanır.$$,
   $$Ablution is ritual purification before acts such as prayer. Its obligations and sunnahs are detailed in fiqh manuals.$$, 1, $$https://islamansiklopedisi.org.tr/abdest$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$fiqh_2$$, $$fiqh$$, $$Cenaze Namazı$$, $$Funeral Prayer$$,
   $$Cenaze namazı Müslüman toplum için farz-ı kifaye kabul edilen bir duadır. Yerel dini otorite ve mezhep uygulamalarına dikkat edilir.$$,
   $$The funeral prayer is a communal obligation and supplication; local religious authority and madhhab practice should be observed.$$, 2, $$https://islamansiklopedisi.org.tr/cenaze-namazi$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),

  ($$ahlak_1$$, $$ahlak$$, $$İslami Erdemler$$, $$Islamic Virtues$$,
   $$Takva, doğruluk, sabır, şükür, merhamet ve adalet Kur'an ve sünnette öne çıkan ahlaki erdemlerdendir.$$,
   $$God-consciousness, truthfulness, patience, gratitude, mercy, and justice are major virtues in the Quran and Sunnah.$$, 1, $$https://islamansiklopedisi.org.tr/ahlak$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$ahlak_2$$, $$ahlak$$, $$Günahlardan Sakınma$$, $$Avoiding Sins$$,
   $$Mümin, açık ve gizli günahlardan sakınmaya; tövbe, kul hakkı hassasiyeti ve helal-haram bilinciyle yaşamaya çağrılır.$$,
   $$A believer is called to avoid public and hidden sins, repent, respect others' rights, and live with halal-haram awareness.$$, 2, $$https://islamansiklopedisi.org.tr/gunah$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$ahlak_3$$, $$ahlak$$, $$Toplumsal İlişkiler$$, $$Social Relationships$$,
   $$Komşuluk, aile, emanet ve sözünde durma gibi ilişkiler İslam ahlakının günlük hayattaki görünür alanlarıdır.$$,
   $$Neighbourliness, family ties, trust, and keeping promises are visible parts of Islamic ethics in daily life.$$, 3, $$https://islamansiklopedisi.org.tr/komsu$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),

  ($$history_1$$, $$history$$, $$İslam'ın Doğuşu$$, $$Rise of Islam$$,
   $$İslam tarihi, vahyin başlaması, Mekke ve Medine dönemleri ve ilk Müslüman toplumun oluşumuyla başlar.$$,
   $$Islamic history begins with revelation, the Meccan and Medinan periods, and the formation of the first Muslim community.$$, 1, $$https://islamansiklopedisi.org.tr/islam$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$history_2$$, $$history$$, $$Endülüs Medeniyeti$$, $$Andalusian Civilization$$,
   $$Endülüs, ilim, mimari ve kültür mirasıyla İslam medeniyet tarihinin önemli tecrübelerinden biridir.$$,
   $$Andalusia is an important experience in Islamic civilization through its scholarly, architectural, and cultural heritage.$$, 2, $$https://islamansiklopedisi.org.tr/endulus$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$history_3$$, $$history$$, $$Osmanlı Devleti$$, $$Ottoman State$$,
   $$Osmanlı tarihi, kurumları, ilim hayatı ve farklı coğrafyalardaki uzun yönetim tecrübesiyle incelenir.$$,
   $$Ottoman history is studied through its institutions, scholarly life, and long administrative experience across regions.$$, 3, $$https://islamansiklopedisi.org.tr/osmanlilar$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),

  ($$mesaj_1$$, $$mesajlar$$, $$Hadis Okuma Bilinci$$, $$Reading Hadith Responsibly$$,
   $$Hadisler kaynak, bağlam ve sıhhat bilgisiyle okunmalıdır. Uygulamadaki hadis kataloğu doğrulanmış kaynak kayıtlarıyla sınırlandırılır.$$,
   $$Hadith should be read with source, context, and authenticity awareness. The app catalog is limited to verified source records.$$, 1, $$https://sunnah.com$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$mesaj_2$$, $$mesajlar$$, $$Kur'an Hakkında$$, $$About the Quran$$,
   $$Kur'an-ı Kerim 114 sureden oluşur. Uygulamadaki ayet metinleri ve çeviriler doğrulanmış kaynak zincirinden alınır.$$,
   $$The Quran consists of 114 surahs. The app's verse text and translations are taken from a verified source chain.$$, 2, $$https://quran.com$$, TIMESTAMPTZ '2026-04-23T00:00:00Z'),
  ($$mesaj_3$$, $$mesajlar$$, $$Müslümanın Günlüğü$$, $$Daily Routine of a Muslim$$,
   $$Günlük hayat; farz ibadetler, helal kazanç, güzel ahlak, dua ve zikirle dengeli bir kulluk bilinci içinde yaşanır.$$,
   $$Daily life is lived with balanced devotion through obligatory worship, lawful earning, good character, supplication, and remembrance.$$, 3, $$https://islamansiklopedisi.org.tr/ibadet$$, TIMESTAMPTZ '2026-04-23T00:00:00Z')
ON CONFLICT (id) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  content = EXCLUDED.content,
  content_en = EXCLUDED.content_en,
  sort_order = EXCLUDED.sort_order,
  source = EXCLUDED.source,
  verified_at = EXCLUDED.verified_at;
