-- Content bootstrap schema for Section 13 live-content rollout.
-- Apply this file before running seed.sql so cloud-first content providers
-- can read from verified public tables with RLS enabled.

create table if not exists public.daily_content (
  id bigint generated by default as identity primary key,
  content_type text not null,
  content_ar text not null,
  content_tr text,
  content_en text,
  reference text not null,
  source text not null,
  display_date date not null,
  verified_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.daily_content
add column if not exists source text;

alter table public.daily_content
add column if not exists verified_at timestamptz;

update public.daily_content
set source = 'legacy://sirat-i-nur/pre-supabase-content'
where source is null or length(trim(source)) = 0;

update public.daily_content
set verified_at = coalesce(verified_at, created_at, timezone('utc', now()))
where verified_at is null;

alter table public.daily_content
alter column source set not null;

alter table public.daily_content
alter column verified_at set not null;

alter table public.daily_content
drop constraint if exists daily_content_display_date_key;

drop index if exists daily_content_display_date_unique_idx;

drop index if exists daily_content_type_display_date_idx;

create unique index if not exists daily_content_type_display_date_unique_idx
on public.daily_content (content_type, display_date);

alter table public.daily_content enable row level security;

drop policy if exists "Public read daily content" on public.daily_content;
create policy "Public read daily content"
on public.daily_content
for select
using (true);

create table if not exists public.live_tv_channels (
  id bigint generated by default as identity primary key,
  short_label text not null unique,
  title text not null,
  subtitle text,
  embed_url text,
  fallback_embed_url text,
  external_url text,
  muted_by_default boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists live_tv_channels_sort_order_idx
on public.live_tv_channels (sort_order);

create unique index if not exists live_tv_channels_short_label_unique_idx
on public.live_tv_channels (short_label);

alter table public.live_tv_channels enable row level security;

drop policy if exists "Public read live tv channels" on public.live_tv_channels;
create policy "Public read live tv channels"
on public.live_tv_channels
for select
using (true);

create table if not exists public.education_categories (
  id text primary key,
  title text not null,
  title_en text,
  icon text,
  description text,
  description_en text,
  sort_order integer not null default 0,
  source text not null check (length(trim(source)) > 0),
  verified_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.education_categories
add column if not exists source text;

alter table public.education_categories
add column if not exists verified_at timestamptz;

update public.education_categories
set source = 'legacy://sirat-i-nur/pre-supabase-content'
where source is null or length(trim(source)) = 0;

update public.education_categories
set verified_at = coalesce(verified_at, created_at, timezone('utc', now()))
where verified_at is null;

alter table public.education_categories
drop constraint if exists education_categories_source_nonempty;

alter table public.education_categories
add constraint education_categories_source_nonempty
check (length(trim(source)) > 0);

alter table public.education_categories
alter column source set not null;

alter table public.education_categories
alter column verified_at set not null;

create index if not exists education_categories_sort_order_idx
on public.education_categories (sort_order);

alter table public.education_categories enable row level security;

drop policy if exists "Public read education categories" on public.education_categories;
create policy "Public read education categories"
on public.education_categories
for select
using (true);

create table if not exists public.education_topics (
  id text primary key,
  category_id text not null references public.education_categories(id) on delete cascade,
  title text not null,
  title_en text,
  content text not null,
  content_en text,
  sort_order integer not null default 0,
  source text not null check (length(trim(source)) > 0),
  verified_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.education_topics
add column if not exists source text;

alter table public.education_topics
add column if not exists verified_at timestamptz;

update public.education_topics
set source = 'legacy://sirat-i-nur/pre-supabase-content'
where source is null or length(trim(source)) = 0;

update public.education_topics
set verified_at = coalesce(verified_at, created_at, timezone('utc', now()))
where verified_at is null;

alter table public.education_topics
drop constraint if exists education_topics_source_nonempty;

alter table public.education_topics
add constraint education_topics_source_nonempty
check (length(trim(source)) > 0);

alter table public.education_topics
alter column source set not null;

alter table public.education_topics
alter column verified_at set not null;

create index if not exists education_topics_category_sort_order_idx
on public.education_topics (category_id, sort_order);

alter table public.education_topics enable row level security;

drop policy if exists "Public read education topics" on public.education_topics;
create policy "Public read education topics"
on public.education_topics
for select
using (true);

create table if not exists public.duas (
  id bigint generated by default as identity primary key,
  title_tr text,
  title_ar text,
  title_en text,
  text_ar text not null,
  transliteration text,
  text_tr text,
  text_en text,
  audio_url text,
  storage_path text,
  category text not null,
  source text not null,
  verified_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.duas
add column if not exists storage_path text;

alter table public.duas
add column if not exists source text;

alter table public.duas
add column if not exists verified_at timestamptz;

update public.duas
set source = 'legacy://sirat-i-nur/pre-supabase-content'
where source is null or length(trim(source)) = 0;

update public.duas
set verified_at = coalesce(verified_at, created_at, timezone('utc', now()))
where verified_at is null;

alter table public.duas
alter column source set not null;

alter table public.duas
alter column verified_at set not null;

create index if not exists duas_category_idx on public.duas (category);

alter table public.duas enable row level security;

drop policy if exists "Public read duas" on public.duas;
create policy "Public read duas"
on public.duas
for select
using (true);

create table if not exists public.asma_ul_husna (
  id smallint primary key,
  name_ar text not null,
  transliteration text not null,
  meaning_tr text,
  meaning_en text,
  audio_url text,
  storage_path text,
  source text not null,
  verified_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.asma_ul_husna
add column if not exists storage_path text;

alter table public.asma_ul_husna
add column if not exists source text;

alter table public.asma_ul_husna
add column if not exists verified_at timestamptz;

update public.asma_ul_husna
set source = 'legacy://sirat-i-nur/pre-supabase-content'
where source is null or length(trim(source)) = 0;

update public.asma_ul_husna
set verified_at = coalesce(verified_at, created_at, timezone('utc', now()))
where verified_at is null;

alter table public.asma_ul_husna
alter column source set not null;

alter table public.asma_ul_husna
alter column verified_at set not null;

alter table public.asma_ul_husna enable row level security;

drop policy if exists "Public read asma ul husna" on public.asma_ul_husna;
create policy "Public read asma ul husna"
on public.asma_ul_husna
for select
using (true);

create table if not exists public.quran_surahs (
  id bigint generated by default as identity primary key,
  surah_number smallint not null unique,
  name_ar text not null,
  name_tr text,
  name_en text,
  name_transliteration text not null,
  ayah_count smallint not null,
  revelation_type text not null,
  source text not null,
  verified_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists quran_surahs_number_idx
on public.quran_surahs (surah_number);

alter table public.quran_surahs
add column if not exists source text;

alter table public.quran_surahs
add column if not exists verified_at timestamptz;

update public.quran_surahs
set source = 'legacy://sirat-i-nur/pre-supabase-content'
where source is null or length(trim(source)) = 0;

update public.quran_surahs
set verified_at = coalesce(verified_at, created_at, timezone('utc', now()))
where verified_at is null;

alter table public.quran_surahs
alter column source set not null;

alter table public.quran_surahs
alter column verified_at set not null;

alter table public.quran_surahs enable row level security;

drop policy if exists "Public read quran surahs" on public.quran_surahs;
create policy "Public read quran surahs"
on public.quran_surahs
for select
using (true);

create table if not exists public.quran_ayahs (
  id bigint generated by default as identity primary key,
  surah_id bigint not null references public.quran_surahs(id) on delete cascade,
  ayah_number smallint not null,
  juz_number smallint,
  text_ar text not null,
  text_tr text,
  text_en text,
  audio_url text,
  source text not null,
  verified_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (surah_id, ayah_number)
);

alter table public.quran_ayahs
add column if not exists juz_number smallint;

alter table public.quran_ayahs
add column if not exists source text;

alter table public.quran_ayahs
add column if not exists verified_at timestamptz;

update public.quran_ayahs
set source = 'legacy://sirat-i-nur/pre-supabase-content'
where source is null or length(trim(source)) = 0;

update public.quran_ayahs
set verified_at = coalesce(verified_at, created_at, timezone('utc', now()))
where verified_at is null;

alter table public.quran_ayahs
alter column source set not null;

alter table public.quran_ayahs
alter column verified_at set not null;

create index if not exists quran_ayahs_surah_number_idx
on public.quran_ayahs (surah_id, ayah_number);

alter table public.quran_ayahs enable row level security;

drop policy if exists "Public read quran ayahs" on public.quran_ayahs;
create policy "Public read quran ayahs"
on public.quran_ayahs
for select
using (true);

create table if not exists public.tafsir_entries (
  id bigint generated by default as identity primary key,
  surah_number smallint not null check (surah_number between 1 and 114),
  ayah_number smallint not null check (ayah_number > 0),
  tafsir_source text not null,
  language text not null,
  tafsir_text text not null check (length(trim(tafsir_text)) > 0),
  source text not null,
  source_license text not null check (length(trim(source_license)) > 0),
  verified_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (surah_number, ayah_number, tafsir_source)
);

alter table public.tafsir_entries
add column if not exists source text;

alter table public.tafsir_entries
add column if not exists source_license text;

alter table public.tafsir_entries
add column if not exists verified_at timestamptz;

alter table public.tafsir_entries
drop constraint if exists tafsir_entries_source_license_nonempty;

update public.tafsir_entries
set source = 'legacy://sirat-i-nur/pre-supabase-content'
where source is null or length(trim(source)) = 0;

update public.tafsir_entries
set source_license = 'Quran.com Terms and Conditions - personal, non-commercial, informational use only (https://quran.com/terms-and-conditions)'
where source_license is null or length(trim(source_license)) = 0;

update public.tafsir_entries
set verified_at = coalesce(verified_at, created_at, timezone('utc', now()))
where verified_at is null;

alter table public.tafsir_entries
add constraint tafsir_entries_source_license_nonempty
check (length(trim(source_license)) > 0);

alter table public.tafsir_entries
alter column source set not null;

alter table public.tafsir_entries
alter column source_license set not null;

alter table public.tafsir_entries
alter column verified_at set not null;

create index if not exists tafsir_entries_source_surah_ayah_idx
on public.tafsir_entries (tafsir_source, surah_number, ayah_number);

alter table public.tafsir_entries enable row level security;

drop policy if exists "Public read tafsir entries" on public.tafsir_entries;
create policy "Public read tafsir entries"
on public.tafsir_entries
for select
using (true);

create table if not exists public.hadiths (
  id bigint generated by default as identity primary key,
  collection_id text not null,
  book text not null,
  hadith_number integer not null check (hadith_number > 0),
  text_ar text not null check (length(trim(text_ar)) > 0),
  text_tr text,
  text_en text,
  narrator text,
  grade text,
  source text not null check (length(trim(source)) > 0),
  source_license text not null check (length(trim(source_license)) > 0),
  verified_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (collection_id, hadith_number)
);

alter table public.hadiths
add column if not exists source text;

alter table public.hadiths
add column if not exists source_license text;

alter table public.hadiths
add column if not exists verified_at timestamptz;

alter table public.hadiths
drop constraint if exists hadiths_source_license_nonempty;

update public.hadiths
set source = 'legacy://sirat-i-nur/pre-supabase-content'
where source is null or length(trim(source)) = 0;

update public.hadiths
set source_license = 'Sunnah.com developers and open platform data access notice (https://sunnah.com/developers)'
where source_license is null or length(trim(source_license)) = 0;

update public.hadiths
set verified_at = coalesce(verified_at, created_at, timezone('utc', now()))
where verified_at is null;

alter table public.hadiths
add constraint hadiths_source_license_nonempty
check (length(trim(source_license)) > 0);

alter table public.hadiths
alter column source set not null;

alter table public.hadiths
alter column source_license set not null;

alter table public.hadiths
alter column verified_at set not null;

create index if not exists hadiths_collection_number_idx
on public.hadiths (collection_id, hadith_number);

alter table public.hadiths enable row level security;

drop policy if exists "Public read hadiths" on public.hadiths;
create policy "Public read hadiths"
on public.hadiths
for select
using (true);

create table if not exists public.audio_files (
  id bigint generated by default as identity primary key,
  type text not null,
  title text not null,
  url text,
  storage_path text,
  surah_number smallint,
  duration_seconds integer,
  reciter text,
  language text,
  source text not null,
  verified_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.audio_files
add column if not exists surah_number smallint;

alter table public.audio_files
add column if not exists source text;

alter table public.audio_files
add column if not exists verified_at timestamptz;

update public.audio_files
set source = 'legacy://sirat-i-nur/pre-supabase-content'
where source is null or length(trim(source)) = 0;

update public.audio_files
set verified_at = coalesce(verified_at, created_at, timezone('utc', now()))
where verified_at is null;

alter table public.audio_files
alter column source set not null;

alter table public.audio_files
alter column verified_at set not null;

create index if not exists audio_files_type_idx
on public.audio_files (type);

create unique index if not exists audio_files_quran_surah_unique_idx
on public.audio_files (type, reciter, surah_number);

alter table public.audio_files enable row level security;

drop policy if exists "Public read audio files" on public.audio_files;
create policy "Public read audio files"
on public.audio_files
for select
using (true);

-- Quran MP3 files are distributed through first-party Cloudflare/GitHub
-- endpoints. Supabase keeps metadata/path rows only, so any legacy Quran
-- Storage bucket must not stay public.
update storage.buckets
set public = false
where id = 'quran-audio';

insert into storage.buckets (id, name, public)
values ('audio-sukun', 'audio-sukun', true)
on conflict (id) do update
set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('audio-dua', 'audio-dua', true)
on conflict (id) do update
set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('audio-adhan', 'audio-adhan', true)
on conflict (id) do update
set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('audio-asma', 'audio-asma', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "Public read quran audio bucket" on storage.objects;

drop policy if exists "Public read sukun audio bucket" on storage.objects;
create policy "Public read sukun audio bucket"
on storage.objects
for select
using (bucket_id = 'audio-sukun');

drop policy if exists "Public read dua audio bucket" on storage.objects;
create policy "Public read dua audio bucket"
on storage.objects
for select
using (bucket_id = 'audio-dua');

drop policy if exists "Public read adhan audio bucket" on storage.objects;
create policy "Public read adhan audio bucket"
on storage.objects
for select
using (bucket_id = 'audio-adhan');

drop policy if exists "Public read asma audio bucket" on storage.objects;
create policy "Public read asma audio bucket"
on storage.objects
for select
using (bucket_id = 'audio-asma');

-- Supabase REST uses PostgREST's schema cache. Reload it after DDL so
-- store-readiness checks can see newly-created tables and columns immediately.
notify pgrst, 'reload schema';
