-- Content bootstrap schema for Section 13 live-content rollout.
-- Apply this file before running seed.sql so cloud-first content providers
-- can read from verified public tables with RLS enabled.

create table if not exists public.duas (
  id bigint generated by default as identity primary key,
  title_tr text,
  title_ar text,
  title_en text,
  text_ar text not null,
  transliteration text,
  text_tr text,
  text_en text,
  audio_url text,
  category text not null,
  source text not null,
  verified_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists duas_category_idx on public.duas (category);

alter table public.duas enable row level security;

drop policy if exists "Public read duas" on public.duas;
create policy "Public read duas"
on public.duas
for select
using (true);

create table if not exists public.asma_ul_husna (
  id smallint primary key,
  name_ar text not null,
  transliteration text not null,
  meaning_tr text,
  meaning_en text,
  audio_url text,
  source text not null,
  verified_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.asma_ul_husna enable row level security;

drop policy if exists "Public read asma ul husna" on public.asma_ul_husna;
create policy "Public read asma ul husna"
on public.asma_ul_husna
for select
using (true);
