import 'dart:convert';
import 'dart:io';

const String chaptersApiUrl =
    'https://api.quran.com/api/v4/chapters?language=en';
const String translationResourcesUrl =
    'https://api.quran.com/api/v4/resources/translations';
const String versesApiBaseUrl =
    'https://api.quran.com/api/v4/verses/by_chapter';
const String outputFileName = 'content_seed_quran_ayahs.sql';

const int turkishTranslationResourceId = 52;
const int englishTranslationResourceId = 85;
const int verseRequestPageSize = 300;
const int seedInsertBatchSize = 400;

Future<void> main() async {
  final client = HttpClient();

  try {
    final chapters = await _fetchChapters(client);
    final translationResources = await _fetchTranslationResources(client);
    final turkishResource = _selectTranslationResource(
      translationResources,
      turkishTranslationResourceId,
      expectedLanguage: 'turkish',
    );
    final englishResource = _selectTranslationResource(
      translationResources,
      englishTranslationResourceId,
      expectedLanguage: 'english',
    );

    if (chapters.length != 114) {
      throw StateError('Expected 114 chapters, got ${chapters.length}.');
    }

    final verifiedAt = DateTime.now().toUtc().toIso8601String();
    final buffer = StringBuffer()
      ..writeln('-- Auto-generated verified Quran ayah seed SQL')
      ..writeln('-- Generated by tool/generate_quran_ayah_seed.dart')
      ..writeln('-- Source API chapters: $chaptersApiUrl')
      ..writeln('-- Source API translations: $translationResourcesUrl')
      ..writeln(
        '-- Source API verses template: '
        '$versesApiBaseUrl/{surah}?fields=text_uthmani&translations='
        '$turkishTranslationResourceId,$englishTranslationResourceId'
        '&per_page=$verseRequestPageSize&page=1',
      )
      ..writeln(
        '-- Turkish resource ($turkishTranslationResourceId): ${turkishResource['name']}',
      )
      ..writeln(
        '-- English resource ($englishTranslationResourceId): ${englishResource['name']}',
      )
      ..writeln('-- Verified at: $verifiedAt')
      ..writeln();

    var totalAyahs = 0;
    final batchRows = <String>[];
    for (final chapter in chapters) {
      final surahNumber = _requiredInt(chapter, 'id');
      final expectedAyahCount = _requiredInt(chapter, 'verses_count');
      final chapterSourceUrl = _buildVerseSourceUrl(surahNumber).toString();
      final verses = await _fetchVerses(client, surahNumber);

      if (verses.length != expectedAyahCount) {
        throw StateError(
          'Surah $surahNumber expected $expectedAyahCount ayahs, '
          'got ${verses.length}.',
        );
      }

      for (var index = 0; index < verses.length; index++) {
        final verse = verses[index];
        final ayahNumber = _requiredInt(verse, 'verse_number');
        final expectedAyahNumber = index + 1;

        if (ayahNumber != expectedAyahNumber) {
          throw StateError(
            'Surah $surahNumber ayah ordering mismatch: '
            'expected $expectedAyahNumber, got $ayahNumber.',
          );
        }

        final textArabic = _requiredString(verse, 'text_uthmani');
        final juzNumber = _requiredInt(verse, 'juz_number');
        final textTurkish = _translationText(
          verse,
          turkishTranslationResourceId,
        );
        final textEnglish = _translationText(
          verse,
          englishTranslationResourceId,
        );

        batchRows.add(
          "  ($surahNumber, $ayahNumber, $juzNumber, '${_escapeSql(textArabic)}', "
          "'${_escapeSql(textTurkish)}', '${_escapeSql(textEnglish)}', "
          "'$chapterSourceUrl', TIMESTAMPTZ '$verifiedAt')",
        );
        if (batchRows.length >= seedInsertBatchSize) {
          _writeAyahBatch(buffer, batchRows);
          batchRows.clear();
        }

        totalAyahs++;
      }
    }

    if (batchRows.isNotEmpty) {
      _writeAyahBatch(buffer, batchRows);
    }

    final file = File(outputFileName);
    await file.writeAsString(buffer.toString());
    stdout.writeln('Generated ${file.path} with $totalAyahs verified ayahs.');
  } finally {
    client.close(force: true);
  }
}

void _writeAyahBatch(StringBuffer buffer, List<String> rows) {
  buffer
    ..writeln('INSERT INTO public.quran_ayahs (')
    ..writeln(
      '  surah_id, ayah_number, juz_number, text_ar, text_tr, text_en, audio_url, source, verified_at',
    )
    ..writeln(')')
    ..writeln('SELECT')
    ..writeln(
      '  surah.id, seed.ayah_number, seed.juz_number, seed.text_ar, seed.text_tr, seed.text_en, NULL, seed.source, seed.verified_at',
    )
    ..writeln('FROM (VALUES')
    ..writeln(rows.join(',\n'))
    ..writeln(
      ') AS seed(surah_number, ayah_number, juz_number, text_ar, text_tr, text_en, source, verified_at)',
    )
    ..writeln(
      'JOIN public.quran_surahs AS surah ON surah.surah_number = seed.surah_number',
    )
    ..writeln('ON CONFLICT (surah_id, ayah_number) DO UPDATE SET')
    ..writeln('  juz_number = EXCLUDED.juz_number,')
    ..writeln('  text_ar = EXCLUDED.text_ar,')
    ..writeln('  text_tr = EXCLUDED.text_tr,')
    ..writeln('  text_en = EXCLUDED.text_en,')
    ..writeln('  audio_url = EXCLUDED.audio_url,')
    ..writeln('  source = EXCLUDED.source,')
    ..writeln('  verified_at = EXCLUDED.verified_at;')
    ..writeln();
}

Future<List<Map<String, dynamic>>> _fetchChapters(HttpClient client) async {
  final payload = await _fetchJsonMap(client, Uri.parse(chaptersApiUrl));
  final chapters = payload['chapters'];

  if (chapters is! List) {
    throw StateError('Missing chapters array in payload from $chaptersApiUrl');
  }

  return chapters.map((row) => Map<String, dynamic>.from(row as Map)).toList();
}

Future<List<Map<String, dynamic>>> _fetchTranslationResources(
  HttpClient client,
) async {
  final payload = await _fetchJsonMap(
    client,
    Uri.parse(translationResourcesUrl),
  );
  final translations = payload['translations'];

  if (translations is! List) {
    throw StateError(
      'Missing translations array in payload from $translationResourcesUrl',
    );
  }

  return translations
      .map((row) => Map<String, dynamic>.from(row as Map))
      .toList();
}

Map<String, dynamic> _selectTranslationResource(
  List<Map<String, dynamic>> resources,
  int resourceId, {
  required String expectedLanguage,
}) {
  for (final resource in resources) {
    if (_requiredInt(resource, 'id') != resourceId) {
      continue;
    }

    final language = _requiredString(resource, 'language_name').toLowerCase();
    if (language != expectedLanguage) {
      throw StateError(
        'Resource $resourceId expected language $expectedLanguage, got $language.',
      );
    }

    return resource;
  }

  throw StateError('Missing translation resource $resourceId.');
}

Future<List<Map<String, dynamic>>> _fetchVerses(
  HttpClient client,
  int surahNumber,
) async {
  final payload = await _fetchJsonMap(
    client,
    _buildVerseSourceUrl(surahNumber),
  );
  final verses = payload['verses'];

  if (verses is! List) {
    throw StateError('Missing verses array for surah $surahNumber.');
  }

  return verses.map((row) => Map<String, dynamic>.from(row as Map)).toList();
}

Uri _buildVerseSourceUrl(int surahNumber) {
  return Uri.parse(
    '$versesApiBaseUrl/$surahNumber?fields=text_uthmani&translations='
    '$turkishTranslationResourceId,$englishTranslationResourceId'
    '&per_page=$verseRequestPageSize&page=1',
  );
}

Future<Map<String, dynamic>> _fetchJsonMap(HttpClient client, Uri uri) async {
  final request = await client.getUrl(uri);
  request.headers.set(HttpHeaders.acceptHeader, 'application/json');
  final response = await request.close();
  final body = await response.transform(utf8.decoder).join();

  if (response.statusCode != HttpStatus.ok) {
    throw HttpException(
      'Unexpected status ${response.statusCode} from $uri',
      uri: uri,
    );
  }

  final decoded = jsonDecode(body);
  if (decoded is! Map<String, dynamic>) {
    throw StateError('Unexpected payload shape from $uri');
  }

  return decoded;
}

String _translationText(Map<String, dynamic> verse, int resourceId) {
  final translations = verse['translations'];
  if (translations is! List) {
    throw StateError('Missing translations array in verse payload.');
  }

  for (final item in translations) {
    final row = Map<String, dynamic>.from(item as Map);
    if (_requiredInt(row, 'resource_id') != resourceId) {
      continue;
    }

    final verseKey = verse['verse_key']?.toString() ?? 'unknown';
    return _normalizeVerifiedTranslation(
      verseKey: verseKey,
      resourceId: resourceId,
      text: _sanitizeTranslation(_requiredString(row, 'text')),
    );
  }

  final verseKey = verse['verse_key']?.toString() ?? 'unknown';
  throw StateError(
    'Missing translation resource $resourceId in verse $verseKey.',
  );
}

String _normalizeVerifiedTranslation({
  required String verseKey,
  required int resourceId,
  required String text,
}) {
  if (verseKey == '2:286' &&
      resourceId == englishTranslationResourceId &&
      text.contains('suffers its bad- ‘ Lord')) {
    return text.replaceFirst(
      'suffers its bad- ‘ Lord',
      'suffers whatever bad it has done. ‘Lord',
    );
  }
  if (verseKey == '3:8' &&
      resourceId == englishTranslationResourceId &&
      text ==
          '‘Our Lord, do not let our hearts deviate after You have guided us. Grant us Your mercy: You are the Ever Giving.') {
    return '$text’';
  }
  if (verseKey == '14:40' &&
      resourceId == turkishTranslationResourceId &&
      text ==
          '"Ey Rabbim! Beni ve soyumdan gelecekleri namazını dosdoğru kılanlardan eyle! Ey Rabbimiz! duamı kabul et!') {
    return '$text"';
  }
  return text;
}

String _sanitizeTranslation(String value) {
  final withoutTags = value.replaceAll(RegExp(r'<[^>]+>'), ' ');
  final decoded = _decodeHtmlEntities(withoutTags);
  return decoded.replaceAll(RegExp(r'\s+'), ' ').trim();
}

String _decodeHtmlEntities(String input) {
  const namedEntities = <String, String>{
    'amp': '&',
    'apos': "'",
    'gt': '>',
    'lt': '<',
    'nbsp': ' ',
    'quot': '"',
  };

  return input.replaceAllMapped(RegExp(r'&(#x?[0-9A-Fa-f]+|[A-Za-z]+);'), (
    match,
  ) {
    final entity = match.group(1)!;
    if (entity.startsWith('#x') || entity.startsWith('#X')) {
      final codePoint = int.tryParse(entity.substring(2), radix: 16);
      return codePoint == null
          ? match.group(0)!
          : String.fromCharCode(codePoint);
    }
    if (entity.startsWith('#')) {
      final codePoint = int.tryParse(entity.substring(1));
      return codePoint == null
          ? match.group(0)!
          : String.fromCharCode(codePoint);
    }
    return namedEntities[entity] ?? match.group(0)!;
  });
}

String _requiredString(Map<String, dynamic> row, String key) {
  final value = row[key]?.toString().trim();
  if (value == null || value.isEmpty) {
    throw StateError('Missing required string field: $key');
  }
  return value;
}

int _requiredInt(Map<String, dynamic> row, String key) {
  final value = row[key];
  if (value is int) {
    return value;
  }
  if (value is num) {
    return value.toInt();
  }
  throw StateError('Missing required int field: $key');
}

String _escapeSql(String value) => value.replaceAll("'", "''");
