import 'dart:convert';
import 'dart:io';

const String sourceApiBaseUrl =
    'https://api.quran.com/api/v4/chapter_recitations';
const String outputFileName = 'content_seed_quran_audio.sql';
const String mirrorSeedAbortMessage =
    'content_seed_quran_audio.sql is mirror input only; generate and apply '
    'content_seed_quran_audio_storage.sql after Storage upload.';

const Map<String, Map<String, Object>> reciters = {
  'abdul_basit_mujawwad': {
    'chapterRecitationId': 1,
    'sourceName': 'AbdulBaset AbdulSamad (Mujawwad)',
  },
  'abdul_basit_murattal': {
    'chapterRecitationId': 2,
    'sourceName': 'AbdulBaset AbdulSamad (Murattal)',
  },
  'sudais': {'chapterRecitationId': 3, 'sourceName': 'Abdur-Rahman as-Sudais'},
  'husary': {
    'chapterRecitationId': 6,
    'sourceName': 'Mahmoud Khalil Al-Husary',
  },
  'alafasy': {
    'chapterRecitationId': 7,
    'sourceName': 'Mishari Rashid al-`Afasy',
  },
  'shuraim': {'chapterRecitationId': 10, 'sourceName': 'Sa`ud ash-Shuraym'},
};

Future<void> main() async {
  final client = HttpClient();

  try {
    final verifiedAt = DateTime.now().toUtc().toIso8601String();
    final buffer = StringBuffer()
      ..writeln('-- Auto-generated verified Quran audio mirror-source SQL')
      ..writeln('-- Generated by tool/generate_quran_audio_seed.dart')
      ..writeln(
        '-- Mirror input only: runtime playback requires storage_path rows',
      )
      ..writeln(
        '-- Generate runtime rows with tool/generate_quran_audio_storage_seed.dart',
      )
      ..writeln('-- Source API base: $sourceApiBaseUrl/{chapter_recitation_id}')
      ..writeln('-- Verified at: $verifiedAt')
      ..writeln('BEGIN;')
      ..writeln('DO \$\$')
      ..writeln('BEGIN')
      ..writeln("  RAISE EXCEPTION '${_escapeSql(mirrorSeedAbortMessage)}';")
      ..writeln('END')
      ..writeln('\$\$;')
      ..writeln();

    var totalRows = 0;
    for (final entry in reciters.entries) {
      final reciterId = entry.key;
      final chapterRecitationId = entry.value['chapterRecitationId']! as int;
      final sourceName = entry.value['sourceName']! as String;
      final sourceUrl = '$sourceApiBaseUrl/$chapterRecitationId';

      final audioFiles = await _fetchAudioFiles(client, chapterRecitationId);
      if (audioFiles.length != 114) {
        throw StateError(
          'Reciter $reciterId expected 114 surah files, got ${audioFiles.length}.',
        );
      }

      for (final audioFile in audioFiles) {
        final surahNumber = _requiredInt(audioFile, 'chapter_id');
        final url = _requiredString(audioFile, 'audio_url');

        buffer
          ..writeln('INSERT INTO public.audio_files (')
          ..writeln(
            '  type, title, url, storage_path, surah_number, duration_seconds, reciter, language, source, verified_at',
          )
          ..writeln(') VALUES (')
          ..writeln(
            "  'quran_surah', 'Surah $surahNumber', '${_escapeSql(url)}', NULL, $surahNumber, NULL, '$reciterId', 'ar', '${_escapeSql(sourceUrl)}', TIMESTAMPTZ '$verifiedAt'",
          )
          ..writeln(') ON CONFLICT (type, reciter, surah_number) DO UPDATE SET')
          ..writeln('  title = EXCLUDED.title,')
          ..writeln('  url = EXCLUDED.url,')
          ..writeln('  storage_path = EXCLUDED.storage_path,')
          ..writeln('  duration_seconds = EXCLUDED.duration_seconds,')
          ..writeln('  language = EXCLUDED.language,')
          ..writeln('  source = EXCLUDED.source,')
          ..writeln('  verified_at = EXCLUDED.verified_at;')
          ..writeln();

        totalRows++;
      }

      buffer.writeln(
        "-- Verified reciter '$reciterId' from $sourceName via $sourceUrl",
      );
      buffer.writeln();
    }

    buffer.writeln('ROLLBACK;');

    final file = File(outputFileName);
    await file.writeAsString(buffer.toString());
    stdout.writeln('Generated ${file.path} with $totalRows audio inserts.');
  } finally {
    client.close(force: true);
  }
}

Future<List<Map<String, dynamic>>> _fetchAudioFiles(
  HttpClient client,
  int chapterRecitationId,
) async {
  final uri = Uri.parse('$sourceApiBaseUrl/$chapterRecitationId');
  final payload = await _fetchJsonMap(client, uri);
  final audioFiles = payload['audio_files'];

  if (audioFiles is! List) {
    throw StateError('Missing audio_files array in payload from $uri');
  }

  final normalized = <int, Map<String, dynamic>>{};
  for (final item in audioFiles) {
    final row = Map<String, dynamic>.from(item as Map);
    final surahNumber = switch (row['chapter_id']) {
      int value => value,
      num value => value.toInt(),
      _ => null,
    };
    final url = row['audio_url']?.toString().trim();
    if (surahNumber == null || surahNumber < 1 || surahNumber > 114) {
      continue;
    }
    if (url == null || url.isEmpty) {
      continue;
    }
    if (normalized.containsKey(surahNumber)) {
      throw StateError(
        'Duplicate chapter_id $surahNumber in payload from $uri.',
      );
    }
    normalized[surahNumber] = row;
  }

  final sorted = normalized.entries.toList()
    ..sort((left, right) => left.key.compareTo(right.key));
  for (var index = 0; index < sorted.length; index++) {
    final expected = index + 1;
    if (sorted[index].key != expected) {
      throw StateError('Missing chapter_id $expected in payload from $uri.');
    }
  }

  return sorted.map((entry) => entry.value).toList();
}

Future<Map<String, dynamic>> _fetchJsonMap(HttpClient client, Uri uri) async {
  final request = await client.getUrl(uri);
  request.headers.set(HttpHeaders.acceptHeader, 'application/json');
  final response = await request.close();
  final body = await response.transform(utf8.decoder).join();

  if (response.statusCode != HttpStatus.ok) {
    throw HttpException(
      'Unexpected status ${response.statusCode} from $uri',
      uri: uri,
    );
  }

  final decoded = jsonDecode(body);
  if (decoded is! Map<String, dynamic>) {
    throw StateError('Unexpected payload shape from $uri');
  }

  return decoded;
}

int _requiredInt(Map<String, dynamic> row, String key) {
  final value = row[key];
  if (value is int) {
    return value;
  }
  if (value is num) {
    return value.toInt();
  }
  throw StateError('Missing required int field: $key');
}

String _requiredString(Map<String, dynamic> row, String key) {
  final value = row[key]?.toString().trim();
  if (value == null || value.isEmpty) {
    throw StateError('Missing required string field: $key');
  }
  return value;
}

String _escapeSql(String value) => value.replaceAll("'", "''");
