import 'dart:convert';
import 'dart:io';

const String sourceDocsUrl =
    'https://api-docs.quran.com/docs/content_apis_versioned/list-chapters/';
const String sourceApiBaseUrl = 'https://api.quran.com/api/v4/chapters';
const String outputFileName = 'content_seed_quran_surahs.sql';

Future<void> main() async {
  final client = HttpClient();

  try {
    final english = await _fetchChapters(client, 'en');
    final turkish = await _fetchChapters(client, 'tr');

    if (english.length != 114 || turkish.length != 114) {
      throw StateError(
        'Expected 114 chapters for both locales, got en=${english.length}, tr=${turkish.length}.',
      );
    }

    final verifiedAt = DateTime.now().toUtc().toIso8601String();
    final buffer = StringBuffer()
      ..writeln('-- Auto-generated verified Quran surah seed SQL')
      ..writeln('-- Generated by tool/generate_quran_surah_seed.dart')
      ..writeln('-- Source docs: $sourceDocsUrl')
      ..writeln('-- Source API EN: $sourceApiBaseUrl?language=en')
      ..writeln('-- Source API TR: $sourceApiBaseUrl?language=tr')
      ..writeln('-- Verified at: $verifiedAt')
      ..writeln();

    for (var i = 0; i < english.length; i++) {
      final enChapter = english[i];
      final trChapter = turkish[i];
      final expectedId = i + 1;

      final enId = enChapter['id'];
      final trId = trChapter['id'];
      if (enId != expectedId || trId != expectedId) {
        throw StateError(
          'Chapter ordering mismatch at index $i: en=$enId, tr=$trId, expected=$expectedId.',
        );
      }

      final surahNumber = expectedId;
      final nameArabic = _requiredString(enChapter, 'name_arabic');
      final nameEnglish = _requiredNestedString(
        enChapter,
        'translated_name',
        'name',
      );
      final nameTurkish = _requiredNestedString(
        trChapter,
        'translated_name',
        'name',
      );
      final transliteration = _requiredString(enChapter, 'name_simple');
      final ayahCount = _requiredInt(enChapter, 'verses_count');
      final revelationType = _normalizeRevelationType(
        _requiredString(enChapter, 'revelation_place'),
      );

      buffer
        ..writeln('INSERT INTO public.quran_surahs (')
        ..writeln(
          '  surah_number, name_ar, name_tr, name_en, name_transliteration, ayah_count, revelation_type, source, verified_at',
        )
        ..writeln(') VALUES (')
        ..writeln(
          "  $surahNumber, '${_escapeSql(nameArabic)}', '${_escapeSql(nameTurkish)}', '${_escapeSql(nameEnglish)}', '${_escapeSql(transliteration)}', $ayahCount, '${_escapeSql(revelationType)}', '$sourceApiBaseUrl', TIMESTAMPTZ '$verifiedAt'",
        )
        ..writeln(') ON CONFLICT (surah_number) DO UPDATE SET')
        ..writeln('  name_ar = EXCLUDED.name_ar,')
        ..writeln('  name_tr = EXCLUDED.name_tr,')
        ..writeln('  name_en = EXCLUDED.name_en,')
        ..writeln('  name_transliteration = EXCLUDED.name_transliteration,')
        ..writeln('  ayah_count = EXCLUDED.ayah_count,')
        ..writeln('  revelation_type = EXCLUDED.revelation_type,')
        ..writeln('  source = EXCLUDED.source,')
        ..writeln('  verified_at = EXCLUDED.verified_at;')
        ..writeln();
    }

    final file = File(outputFileName);
    await file.writeAsString(buffer.toString());
    stdout.writeln('Generated ${file.path} with 114 surah inserts.');
  } finally {
    client.close(force: true);
  }
}

Future<List<Map<String, dynamic>>> _fetchChapters(
  HttpClient client,
  String language,
) async {
  final uri = Uri.parse('$sourceApiBaseUrl?language=$language');
  final request = await client.getUrl(uri);
  request.headers.set(HttpHeaders.acceptHeader, 'application/json');
  final response = await request.close();
  final body = await response.transform(utf8.decoder).join();

  if (response.statusCode != HttpStatus.ok) {
    throw HttpException(
      'Unexpected status ${response.statusCode} from $uri',
      uri: uri,
    );
  }

  final decoded = jsonDecode(body);
  if (decoded is! Map<String, dynamic>) {
    throw StateError('Unexpected payload shape from $uri');
  }

  final chapters = decoded['chapters'];
  if (chapters is! List) {
    throw StateError('Missing chapters array in payload from $uri');
  }

  return chapters.map((row) => Map<String, dynamic>.from(row as Map)).toList();
}

String _requiredString(Map<String, dynamic> row, String key) {
  final value = row[key]?.toString().trim();
  if (value == null || value.isEmpty) {
    throw StateError('Missing required string field: $key');
  }
  return value;
}

String _requiredNestedString(
  Map<String, dynamic> row,
  String nestedKey,
  String key,
) {
  final nested = row[nestedKey];
  if (nested is! Map) {
    throw StateError('Missing required map field: $nestedKey');
  }

  final value = nested[key]?.toString().trim();
  if (value == null || value.isEmpty) {
    throw StateError('Missing required nested string field: $nestedKey.$key');
  }

  return value;
}

int _requiredInt(Map<String, dynamic> row, String key) {
  final value = row[key];
  if (value is int) {
    return value;
  }
  if (value is num) {
    return value.toInt();
  }
  throw StateError('Missing required int field: $key');
}

String _normalizeRevelationType(String revelationPlace) {
  switch (revelationPlace.toLowerCase()) {
    case 'makkah':
      return 'Meccan';
    case 'madinah':
      return 'Medinan';
    default:
      throw StateError('Unexpected revelation_place: $revelationPlace');
  }
}

String _escapeSql(String value) => value.replaceAll("'", "''");
