/// All supported languages with native names for the language picker.
class AppLanguage {
  final String code;
  final String nativeName;
  final String englishName;

  const AppLanguage({
    required this.code,
    required this.nativeName,
    required this.englishName,
  });
}

const List<AppLanguage> supportedLanguages = [
  AppLanguage(code: 'en', nativeName: 'English', englishName: 'English'),
  AppLanguage(code: 'tr', nativeName: 'Türkçe', englishName: 'Turkish'),
  AppLanguage(code: 'ar', nativeName: 'العربية', englishName: 'Arabic'),
  AppLanguage(code: 'de', nativeName: 'Deutsch', englishName: 'German'),
  AppLanguage(code: 'fr', nativeName: 'Français', englishName: 'French'),
  AppLanguage(code: 'es', nativeName: 'Español', englishName: 'Spanish'),
  AppLanguage(code: 'pt', nativeName: 'Português', englishName: 'Portuguese'),
  AppLanguage(code: 'it', nativeName: 'Italiano', englishName: 'Italian'),
  AppLanguage(code: 'nl', nativeName: 'Nederlands', englishName: 'Dutch'),
  AppLanguage(code: 'ru', nativeName: 'Русский', englishName: 'Russian'),
  AppLanguage(code: 'ur', nativeName: 'اردو', englishName: 'Urdu'),
  AppLanguage(code: 'fa', nativeName: 'فارسی', englishName: 'Persian'),
  AppLanguage(code: 'id', nativeName: 'Bahasa Indonesia', englishName: 'Indonesian'),
  AppLanguage(code: 'ms', nativeName: 'Bahasa Melayu', englishName: 'Malay'),
  AppLanguage(code: 'bn', nativeName: 'বাংলা', englishName: 'Bengali'),
  AppLanguage(code: 'bs', nativeName: 'Bosanski', englishName: 'Bosnian'),
  AppLanguage(code: 'zh', nativeName: '中文', englishName: 'Chinese'),
  AppLanguage(code: 'zh_CN', nativeName: '简体中文', englishName: 'Chinese (Simplified)'),
  AppLanguage(code: 'zh_TW', nativeName: '繁體中文', englishName: 'Chinese (Traditional)'),
  AppLanguage(code: 'ja', nativeName: '日本語', englishName: 'Japanese'),
  AppLanguage(code: 'ko', nativeName: '한국어', englishName: 'Korean'),
  AppLanguage(code: 'sw', nativeName: 'Kiswahili', englishName: 'Swahili'),
  AppLanguage(code: 'hi', nativeName: 'हिन्दी', englishName: 'Hindi'),
  AppLanguage(code: 'uz', nativeName: 'Oʻzbekcha', englishName: 'Uzbek'),
  AppLanguage(code: 'az', nativeName: 'Azərbaycanca', englishName: 'Azerbaijani'),
  AppLanguage(code: 'kk', nativeName: 'Қазақша', englishName: 'Kazakh'),
  AppLanguage(code: 'sq', nativeName: 'Shqip', englishName: 'Albanian'),
  AppLanguage(code: 'so', nativeName: 'Soomaaliga', englishName: 'Somali'),
  AppLanguage(code: 'ps', nativeName: 'پښتو', englishName: 'Pashto'),
  AppLanguage(code: 'ku', nativeName: 'Kurdî', englishName: 'Kurdish'),
  AppLanguage(code: 'ha', nativeName: 'Hausa', englishName: 'Hausa'),
  AppLanguage(code: 'am', nativeName: 'አማርኛ', englishName: 'Amharic'),
  AppLanguage(code: 'th', nativeName: 'ไทย', englishName: 'Thai'),
  AppLanguage(code: 'tl', nativeName: 'Tagalog', englishName: 'Tagalog'),
  AppLanguage(code: 'ta', nativeName: 'தமிழ்', englishName: 'Tamil'),
  AppLanguage(code: 'pl', nativeName: 'Polski', englishName: 'Polish'),
  AppLanguage(code: 'uk', nativeName: 'Українська', englishName: 'Ukrainian'),
  AppLanguage(code: 'ro', nativeName: 'Română', englishName: 'Romanian'),
  AppLanguage(code: 'bg', nativeName: 'Български', englishName: 'Bulgarian'),
  AppLanguage(code: 'el', nativeName: 'Ελληνικά', englishName: 'Greek'),
  AppLanguage(code: 'tg', nativeName: 'Тоҷикӣ', englishName: 'Tajik'),
  AppLanguage(code: 'tk', nativeName: 'Türkmençe', englishName: 'Turkmen'),
  AppLanguage(code: 'wo', nativeName: 'Wolof', englishName: 'Wolof'),
  AppLanguage(code: 'sd', nativeName: 'سنڌي', englishName: 'Sindhi'),
  // Standard Fallbacks
  AppLanguage(code: 'aa', nativeName: 'AA', englishName: 'AA'),
  AppLanguage(code: 'ab', nativeName: 'AB', englishName: 'AB'),
  AppLanguage(code: 'ae', nativeName: 'AE', englishName: 'AE'),
  AppLanguage(code: 'af', nativeName: 'AF', englishName: 'AF'),
  AppLanguage(code: 'ak', nativeName: 'AK', englishName: 'AK'),
  AppLanguage(code: 'an', nativeName: 'AN', englishName: 'AN'),
  AppLanguage(code: 'as', nativeName: 'AS', englishName: 'AS'),
  AppLanguage(code: 'av', nativeName: 'AV', englishName: 'AV'),
  AppLanguage(code: 'ay', nativeName: 'AY', englishName: 'AY'),
  AppLanguage(code: 'ba', nativeName: 'BA', englishName: 'BA'),
  AppLanguage(code: 'be', nativeName: 'BE', englishName: 'BE'),
  AppLanguage(code: 'bh', nativeName: 'BH', englishName: 'BH'),
  AppLanguage(code: 'bi', nativeName: 'BI', englishName: 'BI'),
  AppLanguage(code: 'bm', nativeName: 'BM', englishName: 'BM'),
  AppLanguage(code: 'bo', nativeName: 'BO', englishName: 'BO'),
  AppLanguage(code: 'br', nativeName: 'BR', englishName: 'BR'),
  AppLanguage(code: 'ca', nativeName: 'CA', englishName: 'CA'),
  AppLanguage(code: 'ce', nativeName: 'CE', englishName: 'CE'),
  AppLanguage(code: 'ceb', nativeName: 'CEB', englishName: 'CEB'),
  AppLanguage(code: 'ch', nativeName: 'CH', englishName: 'CH'),
  AppLanguage(code: 'co', nativeName: 'CO', englishName: 'CO'),
  AppLanguage(code: 'cr', nativeName: 'CR', englishName: 'CR'),
  AppLanguage(code: 'cs', nativeName: 'CS', englishName: 'CS'),
  AppLanguage(code: 'cu', nativeName: 'CU', englishName: 'CU'),
  AppLanguage(code: 'cv', nativeName: 'CV', englishName: 'CV'),
  AppLanguage(code: 'cy', nativeName: 'CY', englishName: 'CY'),
  AppLanguage(code: 'da', nativeName: 'DA', englishName: 'DA'),
  AppLanguage(code: 'dv', nativeName: 'DV', englishName: 'DV'),
  AppLanguage(code: 'dz', nativeName: 'DZ', englishName: 'DZ'),
  AppLanguage(code: 'ee', nativeName: 'EE', englishName: 'EE'),
  AppLanguage(code: 'eo', nativeName: 'EO', englishName: 'EO'),
  AppLanguage(code: 'et', nativeName: 'ET', englishName: 'ET'),
  AppLanguage(code: 'eu', nativeName: 'EU', englishName: 'EU'),
  AppLanguage(code: 'ff', nativeName: 'FF', englishName: 'FF'),
  AppLanguage(code: 'fi', nativeName: 'FI', englishName: 'FI'),
  AppLanguage(code: 'fj', nativeName: 'FJ', englishName: 'FJ'),
  AppLanguage(code: 'fo', nativeName: 'FO', englishName: 'FO'),
  AppLanguage(code: 'fy', nativeName: 'FY', englishName: 'FY'),
  AppLanguage(code: 'ga', nativeName: 'GA', englishName: 'GA'),
  AppLanguage(code: 'gd', nativeName: 'GD', englishName: 'GD'),
  AppLanguage(code: 'gl', nativeName: 'GL', englishName: 'GL'),
  AppLanguage(code: 'gn', nativeName: 'GN', englishName: 'GN'),
  AppLanguage(code: 'gu', nativeName: 'GU', englishName: 'GU'),
  AppLanguage(code: 'gv', nativeName: 'GV', englishName: 'GV'),
  AppLanguage(code: 'haw', nativeName: 'HAW', englishName: 'HAW'),
  AppLanguage(code: 'he', nativeName: 'HE', englishName: 'HE'),
  AppLanguage(code: 'ho', nativeName: 'HO', englishName: 'HO'),
  AppLanguage(code: 'hr', nativeName: 'HR', englishName: 'HR'),
  AppLanguage(code: 'ht', nativeName: 'HT', englishName: 'HT'),
  AppLanguage(code: 'hu', nativeName: 'HU', englishName: 'HU'),
  AppLanguage(code: 'hy', nativeName: 'HY', englishName: 'HY'),
  AppLanguage(code: 'hz', nativeName: 'HZ', englishName: 'HZ'),
  AppLanguage(code: 'ia', nativeName: 'IA', englishName: 'IA'),
  AppLanguage(code: 'ie', nativeName: 'IE', englishName: 'IE'),
  AppLanguage(code: 'ig', nativeName: 'IG', englishName: 'IG'),
  AppLanguage(code: 'ii', nativeName: 'II', englishName: 'II'),
  AppLanguage(code: 'ik', nativeName: 'IK', englishName: 'IK'),
  AppLanguage(code: 'io', nativeName: 'IO', englishName: 'IO'),
  AppLanguage(code: 'is', nativeName: 'IS', englishName: 'IS'),
  AppLanguage(code: 'iu', nativeName: 'IU', englishName: 'IU'),
  AppLanguage(code: 'jv', nativeName: 'JV', englishName: 'JV'),
  AppLanguage(code: 'ka', nativeName: 'KA', englishName: 'KA'),
  AppLanguage(code: 'kg', nativeName: 'KG', englishName: 'KG'),
  AppLanguage(code: 'ki', nativeName: 'KI', englishName: 'KI'),
  AppLanguage(code: 'kj', nativeName: 'KJ', englishName: 'KJ'),
  AppLanguage(code: 'kl', nativeName: 'KL', englishName: 'KL'),
  AppLanguage(code: 'km', nativeName: 'KM', englishName: 'KM'),
  AppLanguage(code: 'kn', nativeName: 'KN', englishName: 'KN'),
  AppLanguage(code: 'kr', nativeName: 'KR', englishName: 'KR'),
  AppLanguage(code: 'ks', nativeName: 'KS', englishName: 'KS'),
  AppLanguage(code: 'kv', nativeName: 'KV', englishName: 'KV'),
  AppLanguage(code: 'kw', nativeName: 'KW', englishName: 'KW'),
  AppLanguage(code: 'ky', nativeName: 'KY', englishName: 'KY'),
  AppLanguage(code: 'la', nativeName: 'LA', englishName: 'LA'),
  AppLanguage(code: 'lb', nativeName: 'LB', englishName: 'LB'),
  AppLanguage(code: 'lg', nativeName: 'LG', englishName: 'LG'),
  AppLanguage(code: 'li', nativeName: 'LI', englishName: 'LI'),
  AppLanguage(code: 'ln', nativeName: 'LN', englishName: 'LN'),
  AppLanguage(code: 'lo', nativeName: 'LO', englishName: 'LO'),
  AppLanguage(code: 'lt', nativeName: 'LT', englishName: 'LT'),
  AppLanguage(code: 'lu', nativeName: 'LU', englishName: 'LU'),
  AppLanguage(code: 'lv', nativeName: 'LV', englishName: 'LV'),
  AppLanguage(code: 'mg', nativeName: 'MG', englishName: 'MG'),
  AppLanguage(code: 'mh', nativeName: 'MH', englishName: 'MH'),
  AppLanguage(code: 'mi', nativeName: 'MI', englishName: 'MI'),
  AppLanguage(code: 'mk', nativeName: 'MK', englishName: 'MK'),
  AppLanguage(code: 'ml', nativeName: 'ML', englishName: 'ML'),
  AppLanguage(code: 'mn', nativeName: 'MN', englishName: 'MN'),
  AppLanguage(code: 'mr', nativeName: 'MR', englishName: 'MR'),
  AppLanguage(code: 'mt', nativeName: 'MT', englishName: 'MT'),
  AppLanguage(code: 'my', nativeName: 'MY', englishName: 'MY'),
  AppLanguage(code: 'na', nativeName: 'NA', englishName: 'NA'),
  AppLanguage(code: 'nb', nativeName: 'NB', englishName: 'NB'),
  AppLanguage(code: 'nd', nativeName: 'ND', englishName: 'ND'),
  AppLanguage(code: 'ne', nativeName: 'NE', englishName: 'NE'),
  AppLanguage(code: 'ng', nativeName: 'NG', englishName: 'NG'),
  AppLanguage(code: 'nn', nativeName: 'NN', englishName: 'NN'),
  AppLanguage(code: 'no', nativeName: 'NO', englishName: 'NO'),
  AppLanguage(code: 'nr', nativeName: 'NR', englishName: 'NR'),
  AppLanguage(code: 'nv', nativeName: 'NV', englishName: 'NV'),
  AppLanguage(code: 'ny', nativeName: 'NY', englishName: 'NY'),
  AppLanguage(code: 'oc', nativeName: 'OC', englishName: 'OC'),
  AppLanguage(code: 'oj', nativeName: 'OJ', englishName: 'OJ'),
  AppLanguage(code: 'om', nativeName: 'OM', englishName: 'OM'),
  AppLanguage(code: 'or', nativeName: 'OR', englishName: 'OR'),
  AppLanguage(code: 'os', nativeName: 'OS', englishName: 'OS'),
  AppLanguage(code: 'pa', nativeName: 'PA', englishName: 'PA'),
  AppLanguage(code: 'pi', nativeName: 'PI', englishName: 'PI'),
  AppLanguage(code: 'qu', nativeName: 'QU', englishName: 'QU'),
  AppLanguage(code: 'rm', nativeName: 'RM', englishName: 'RM'),
  AppLanguage(code: 'rn', nativeName: 'RN', englishName: 'RN'),
  AppLanguage(code: 'rw', nativeName: 'RW', englishName: 'RW'),
  AppLanguage(code: 'sa', nativeName: 'SA', englishName: 'SA'),
  AppLanguage(code: 'sc', nativeName: 'SC', englishName: 'SC'),
  AppLanguage(code: 'se', nativeName: 'SE', englishName: 'SE'),
  AppLanguage(code: 'sg', nativeName: 'SG', englishName: 'SG'),
  AppLanguage(code: 'si', nativeName: 'SI', englishName: 'SI'),
  AppLanguage(code: 'sk', nativeName: 'SK', englishName: 'SK'),
  AppLanguage(code: 'sl', nativeName: 'SL', englishName: 'SL'),
  AppLanguage(code: 'sm', nativeName: 'SM', englishName: 'SM'),
  AppLanguage(code: 'sn', nativeName: 'SN', englishName: 'SN'),
  AppLanguage(code: 'sr', nativeName: 'SR', englishName: 'SR'),
  AppLanguage(code: 'ss', nativeName: 'SS', englishName: 'SS'),
  AppLanguage(code: 'st', nativeName: 'ST', englishName: 'ST'),
  AppLanguage(code: 'su', nativeName: 'SU', englishName: 'SU'),
  AppLanguage(code: 'sv', nativeName: 'SV', englishName: 'SV'),
  AppLanguage(code: 'te', nativeName: 'TE', englishName: 'TE'),
  AppLanguage(code: 'ti', nativeName: 'TI', englishName: 'TI'),
  AppLanguage(code: 'tn', nativeName: 'TN', englishName: 'TN'),
  AppLanguage(code: 'to', nativeName: 'TO', englishName: 'TO'),
  AppLanguage(code: 'ts', nativeName: 'TS', englishName: 'TS'),
  AppLanguage(code: 'tt', nativeName: 'TT', englishName: 'TT'),
  AppLanguage(code: 'tw', nativeName: 'TW', englishName: 'TW'),
  AppLanguage(code: 'ty', nativeName: 'TY', englishName: 'TY'),
  AppLanguage(code: 'ug', nativeName: 'UG', englishName: 'UG'),
  AppLanguage(code: 've', nativeName: 'VE', englishName: 'VE'),
  AppLanguage(code: 'vi', nativeName: 'VI', englishName: 'VI'),
  AppLanguage(code: 'vo', nativeName: 'VO', englishName: 'VO'),
  AppLanguage(code: 'wa', nativeName: 'WA', englishName: 'WA'),
  AppLanguage(code: 'xh', nativeName: 'XH', englishName: 'XH'),
  AppLanguage(code: 'yi', nativeName: 'YI', englishName: 'YI'),
  AppLanguage(code: 'yo', nativeName: 'YO', englishName: 'YO'),
  AppLanguage(code: 'za', nativeName: 'ZA', englishName: 'ZA'),
  AppLanguage(code: 'zu', nativeName: 'ZU', englishName: 'ZU'),
];

/// Comprehensive global city database with timezone offsets, countries, and coordinates.
class CityData {
  final String name;
  final String country;
  final String countryCode;
  final double lat;
  final double lng;
  final String timezone;

  const CityData({
    required this.name,
    required this.country,
    required this.countryCode,
    required this.lat,
    required this.lng,
    required this.timezone,
  });
}

const List<CityData> globalCities = [
  // Turkey
  CityData(name: 'Istanbul', country: 'Turkey', countryCode: 'TR', lat: 41.0082, lng: 28.9784, timezone: 'Europe/Istanbul'),
  CityData(name: 'Ankara', country: 'Turkey', countryCode: 'TR', lat: 39.9334, lng: 32.8597, timezone: 'Europe/Istanbul'),
  CityData(name: 'Izmir', country: 'Turkey', countryCode: 'TR', lat: 38.4192, lng: 27.1287, timezone: 'Europe/Istanbul'),
  CityData(name: 'Bursa', country: 'Turkey', countryCode: 'TR', lat: 40.1826, lng: 29.0665, timezone: 'Europe/Istanbul'),
  CityData(name: 'Konya', country: 'Turkey', countryCode: 'TR', lat: 37.8746, lng: 32.4932, timezone: 'Europe/Istanbul'),
  CityData(name: 'Antalya', country: 'Turkey', countryCode: 'TR', lat: 36.8844, lng: 30.7056, timezone: 'Europe/Istanbul'),
  // Saudi Arabia
  CityData(name: 'Makkah', country: 'Saudi Arabia', countryCode: 'SA', lat: 21.3891, lng: 39.8579, timezone: 'Asia/Riyadh'),
  CityData(name: 'Madinah', country: 'Saudi Arabia', countryCode: 'SA', lat: 24.5247, lng: 39.5692, timezone: 'Asia/Riyadh'),
  CityData(name: 'Riyadh', country: 'Saudi Arabia', countryCode: 'SA', lat: 24.7136, lng: 46.6753, timezone: 'Asia/Riyadh'),
  CityData(name: 'Jeddah', country: 'Saudi Arabia', countryCode: 'SA', lat: 21.5433, lng: 39.1728, timezone: 'Asia/Riyadh'),
  // Egypt
  CityData(name: 'Cairo', country: 'Egypt', countryCode: 'EG', lat: 30.0444, lng: 31.2357, timezone: 'Africa/Cairo'),
  CityData(name: 'Alexandria', country: 'Egypt', countryCode: 'EG', lat: 31.2001, lng: 29.9187, timezone: 'Africa/Cairo'),
  // UAE
  CityData(name: 'Dubai', country: 'UAE', countryCode: 'AE', lat: 25.2048, lng: 55.2708, timezone: 'Asia/Dubai'),
  CityData(name: 'Abu Dhabi', country: 'UAE', countryCode: 'AE', lat: 24.4539, lng: 54.3773, timezone: 'Asia/Dubai'),
  // Pakistan
  CityData(name: 'Islamabad', country: 'Pakistan', countryCode: 'PK', lat: 33.6844, lng: 73.0479, timezone: 'Asia/Karachi'),
  CityData(name: 'Karachi', country: 'Pakistan', countryCode: 'PK', lat: 24.8607, lng: 67.0011, timezone: 'Asia/Karachi'),
  CityData(name: 'Lahore', country: 'Pakistan', countryCode: 'PK', lat: 31.5497, lng: 74.3436, timezone: 'Asia/Karachi'),
  // Indonesia / Malaysia
  CityData(name: 'Jakarta', country: 'Indonesia', countryCode: 'ID', lat: -6.2088, lng: 106.8456, timezone: 'Asia/Jakarta'),
  CityData(name: 'Kuala Lumpur', country: 'Malaysia', countryCode: 'MY', lat: 3.1390, lng: 101.6869, timezone: 'Asia/Kuala_Lumpur'),
  // Bangladesh
  CityData(name: 'Dhaka', country: 'Bangladesh', countryCode: 'BD', lat: 23.8103, lng: 90.4125, timezone: 'Asia/Dhaka'),
  // Iran
  CityData(name: 'Tehran', country: 'Iran', countryCode: 'IR', lat: 35.6892, lng: 51.3890, timezone: 'Asia/Tehran'),
  // Iraq / Jordan / Syria
  CityData(name: 'Baghdad', country: 'Iraq', countryCode: 'IQ', lat: 33.3152, lng: 44.3661, timezone: 'Asia/Baghdad'),
  CityData(name: 'Amman', country: 'Jordan', countryCode: 'JO', lat: 31.9454, lng: 35.9284, timezone: 'Asia/Amman'),
  CityData(name: 'Damascus', country: 'Syria', countryCode: 'SY', lat: 33.5138, lng: 36.2765, timezone: 'Asia/Damascus'),
  CityData(name: 'Jerusalem', country: 'Palestine', countryCode: 'PS', lat: 31.7683, lng: 35.2137, timezone: 'Asia/Jerusalem'),
  // North Africa
  CityData(name: 'Casablanca', country: 'Morocco', countryCode: 'MA', lat: 33.5731, lng: -7.5898, timezone: 'Africa/Casablanca'),
  CityData(name: 'Tunis', country: 'Tunisia', countryCode: 'TN', lat: 36.8065, lng: 10.1815, timezone: 'Africa/Tunis'),
  CityData(name: 'Algiers', country: 'Algeria', countryCode: 'DZ', lat: 36.7372, lng: 3.0863, timezone: 'Africa/Algiers'),
  // Sub-Saharan Africa
  CityData(name: 'Lagos', country: 'Nigeria', countryCode: 'NG', lat: 6.5244, lng: 3.3792, timezone: 'Africa/Lagos'),
  CityData(name: 'Nairobi', country: 'Kenya', countryCode: 'KE', lat: -1.2921, lng: 36.8219, timezone: 'Africa/Nairobi'),
  CityData(name: 'Dar es Salaam', country: 'Tanzania', countryCode: 'TZ', lat: -6.7924, lng: 39.2083, timezone: 'Africa/Dar_es_Salaam'),
  CityData(name: 'Cape Town', country: 'South Africa', countryCode: 'ZA', lat: -33.9249, lng: 18.4241, timezone: 'Africa/Johannesburg'),
  // Europe
  CityData(name: 'London', country: 'United Kingdom', countryCode: 'GB', lat: 51.5074, lng: -0.1278, timezone: 'Europe/London'),
  CityData(name: 'Berlin', country: 'Germany', countryCode: 'DE', lat: 52.5200, lng: 13.4050, timezone: 'Europe/Berlin'),
  CityData(name: 'Paris', country: 'France', countryCode: 'FR', lat: 48.8566, lng: 2.3522, timezone: 'Europe/Paris'),
  CityData(name: 'Amsterdam', country: 'Netherlands', countryCode: 'NL', lat: 52.3676, lng: 4.9041, timezone: 'Europe/Amsterdam'),
  CityData(name: 'Madrid', country: 'Spain', countryCode: 'ES', lat: 40.4168, lng: -3.7038, timezone: 'Europe/Madrid'),
  CityData(name: 'Rome', country: 'Italy', countryCode: 'IT', lat: 41.9028, lng: 12.4964, timezone: 'Europe/Rome'),
  CityData(name: 'Vienna', country: 'Austria', countryCode: 'AT', lat: 48.2082, lng: 16.3738, timezone: 'Europe/Vienna'),
  CityData(name: 'Brussels', country: 'Belgium', countryCode: 'BE', lat: 50.8503, lng: 4.3517, timezone: 'Europe/Brussels'),
  CityData(name: 'Stockholm', country: 'Sweden', countryCode: 'SE', lat: 59.3293, lng: 18.0686, timezone: 'Europe/Stockholm'),
  CityData(name: 'Oslo', country: 'Norway', countryCode: 'NO', lat: 59.9139, lng: 10.7522, timezone: 'Europe/Oslo'),
  CityData(name: 'Sarajevo', country: 'Bosnia', countryCode: 'BA', lat: 43.8563, lng: 18.4131, timezone: 'Europe/Sarajevo'),
  CityData(name: 'Moscow', country: 'Russia', countryCode: 'RU', lat: 55.7558, lng: 37.6173, timezone: 'Europe/Moscow'),
  // Americas
  CityData(name: 'New York', country: 'United States', countryCode: 'US', lat: 40.7128, lng: -74.0060, timezone: 'America/New_York'),
  CityData(name: 'Los Angeles', country: 'United States', countryCode: 'US', lat: 34.0522, lng: -118.2437, timezone: 'America/Los_Angeles'),
  CityData(name: 'Toronto', country: 'Canada', countryCode: 'CA', lat: 43.6532, lng: -79.3832, timezone: 'America/Toronto'),
  CityData(name: 'São Paulo', country: 'Brazil', countryCode: 'BR', lat: -23.5505, lng: -46.6333, timezone: 'America/Sao_Paulo'),
  CityData(name: 'Buenos Aires', country: 'Argentina', countryCode: 'AR', lat: -34.6037, lng: -58.3816, timezone: 'America/Argentina/Buenos_Aires'),
  // Central/South Asia
  CityData(name: 'Tashkent', country: 'Uzbekistan', countryCode: 'UZ', lat: 41.2995, lng: 69.2401, timezone: 'Asia/Tashkent'),
  CityData(name: 'Baku', country: 'Azerbaijan', countryCode: 'AZ', lat: 40.4093, lng: 49.8671, timezone: 'Asia/Baku'),
  CityData(name: 'Kabul', country: 'Afghanistan', countryCode: 'AF', lat: 34.5553, lng: 69.2075, timezone: 'Asia/Kabul'),
  // East Asia / Oceania
  CityData(name: 'Tokyo', country: 'Japan', countryCode: 'JP', lat: 35.6762, lng: 139.6503, timezone: 'Asia/Tokyo'),
  CityData(name: 'Seoul', country: 'South Korea', countryCode: 'KR', lat: 37.5665, lng: 126.9780, timezone: 'Asia/Seoul'),
  CityData(name: 'Beijing', country: 'China', countryCode: 'CN', lat: 39.9042, lng: 116.4074, timezone: 'Asia/Shanghai'),
  CityData(name: 'Sydney', country: 'Australia', countryCode: 'AU', lat: -33.8688, lng: 151.2093, timezone: 'Australia/Sydney'),
  CityData(name: 'Auckland', country: 'New Zealand', countryCode: 'NZ', lat: -36.8485, lng: 174.7633, timezone: 'Pacific/Auckland'),
  // Kuwait / Qatar / Bahrain / Oman
  CityData(name: 'Kuwait City', country: 'Kuwait', countryCode: 'KW', lat: 29.3759, lng: 47.9774, timezone: 'Asia/Kuwait'),
  CityData(name: 'Doha', country: 'Qatar', countryCode: 'QA', lat: 25.2854, lng: 51.5310, timezone: 'Asia/Qatar'),
  CityData(name: 'Manama', country: 'Bahrain', countryCode: 'BH', lat: 26.2285, lng: 50.5860, timezone: 'Asia/Bahrain'),
  CityData(name: 'Muscat', country: 'Oman', countryCode: 'OM', lat: 23.5880, lng: 58.3829, timezone: 'Asia/Muscat'),
];


