/// Complete Quran Surah metadata (114 surahs)
class SurahData {
  final int number;
  final String nameArabic;
  final String nameEnglish;
  final String nameTurkish;
  final String transliteration;
  final int ayahCount;
  final String revelationType; // Meccan or Medinan
  final int revelationOrder;

  const SurahData({
    required this.number,
    required this.nameArabic,
    required this.nameEnglish,
    required this.nameTurkish,
    required this.transliteration,
    required this.ayahCount,
    required this.revelationType,
    required this.revelationOrder,
  });
}

const List<SurahData> allSurahs = [
  SurahData(number: 1, nameArabic: 'الفاتحة', nameEnglish: 'The Opening', nameTurkish: 'Fatiha', transliteration: 'Al-Fatihah', ayahCount: 7, revelationType: 'Meccan', revelationOrder: 5),
  SurahData(number: 2, nameArabic: 'البقرة', nameEnglish: 'The Cow', nameTurkish: 'Bakara', transliteration: 'Al-Baqarah', ayahCount: 286, revelationType: 'Medinan', revelationOrder: 87),
  SurahData(number: 3, nameArabic: 'آل عمران', nameEnglish: 'The Family of Imran', nameTurkish: 'Al-i Imran', transliteration: 'Ali Imran', ayahCount: 200, revelationType: 'Medinan', revelationOrder: 89),
  SurahData(number: 4, nameArabic: 'النساء', nameEnglish: 'The Women', nameTurkish: 'Nisa', transliteration: 'An-Nisa', ayahCount: 176, revelationType: 'Medinan', revelationOrder: 92),
  SurahData(number: 5, nameArabic: 'المائدة', nameEnglish: 'The Table Spread', nameTurkish: 'Maide', transliteration: 'Al-Ma\'idah', ayahCount: 120, revelationType: 'Medinan', revelationOrder: 112),
  SurahData(number: 6, nameArabic: 'الأنعام', nameEnglish: 'The Cattle', nameTurkish: 'Enam', transliteration: 'Al-An\'am', ayahCount: 165, revelationType: 'Meccan', revelationOrder: 55),
  SurahData(number: 7, nameArabic: 'الأعراف', nameEnglish: 'The Heights', nameTurkish: 'Araf', transliteration: 'Al-A\'raf', ayahCount: 206, revelationType: 'Meccan', revelationOrder: 39),
  SurahData(number: 8, nameArabic: 'الأنفال', nameEnglish: 'The Spoils of War', nameTurkish: 'Enfal', transliteration: 'Al-Anfal', ayahCount: 75, revelationType: 'Medinan', revelationOrder: 88),
  SurahData(number: 9, nameArabic: 'التوبة', nameEnglish: 'The Repentance', nameTurkish: 'Tevbe', transliteration: 'At-Tawbah', ayahCount: 129, revelationType: 'Medinan', revelationOrder: 113),
  SurahData(number: 10, nameArabic: 'يونس', nameEnglish: 'Jonah', nameTurkish: 'Yunus', transliteration: 'Yunus', ayahCount: 109, revelationType: 'Meccan', revelationOrder: 51),
  SurahData(number: 11, nameArabic: 'هود', nameEnglish: 'Hud', nameTurkish: 'Hud', transliteration: 'Hud', ayahCount: 123, revelationType: 'Meccan', revelationOrder: 52),
  SurahData(number: 12, nameArabic: 'يوسف', nameEnglish: 'Joseph', nameTurkish: 'Yusuf', transliteration: 'Yusuf', ayahCount: 111, revelationType: 'Meccan', revelationOrder: 53),
  SurahData(number: 13, nameArabic: 'الرعد', nameEnglish: 'The Thunder', nameTurkish: 'Rad', transliteration: 'Ar-Ra\'d', ayahCount: 43, revelationType: 'Medinan', revelationOrder: 96),
  SurahData(number: 14, nameArabic: 'إبراهيم', nameEnglish: 'Abraham', nameTurkish: 'Ibrahim', transliteration: 'Ibrahim', ayahCount: 52, revelationType: 'Meccan', revelationOrder: 72),
  SurahData(number: 15, nameArabic: 'الحجر', nameEnglish: 'The Rocky Tract', nameTurkish: 'Hicr', transliteration: 'Al-Hijr', ayahCount: 99, revelationType: 'Meccan', revelationOrder: 54),
  SurahData(number: 16, nameArabic: 'النحل', nameEnglish: 'The Bee', nameTurkish: 'Nahl', transliteration: 'An-Nahl', ayahCount: 128, revelationType: 'Meccan', revelationOrder: 70),
  SurahData(number: 17, nameArabic: 'الإسراء', nameEnglish: 'The Night Journey', nameTurkish: 'Isra', transliteration: 'Al-Isra', ayahCount: 111, revelationType: 'Meccan', revelationOrder: 50),
  SurahData(number: 18, nameArabic: 'الكهف', nameEnglish: 'The Cave', nameTurkish: 'Kehf', transliteration: 'Al-Kahf', ayahCount: 110, revelationType: 'Meccan', revelationOrder: 69),
  SurahData(number: 19, nameArabic: 'مريم', nameEnglish: 'Mary', nameTurkish: 'Meryem', transliteration: 'Maryam', ayahCount: 98, revelationType: 'Meccan', revelationOrder: 44),
  SurahData(number: 20, nameArabic: 'طه', nameEnglish: 'Ta-Ha', nameTurkish: 'Taha', transliteration: 'Ta-Ha', ayahCount: 135, revelationType: 'Meccan', revelationOrder: 45),
  SurahData(number: 21, nameArabic: 'الأنبياء', nameEnglish: 'The Prophets', nameTurkish: 'Enbiya', transliteration: 'Al-Anbiya', ayahCount: 112, revelationType: 'Meccan', revelationOrder: 73),
  SurahData(number: 22, nameArabic: 'الحج', nameEnglish: 'The Pilgrimage', nameTurkish: 'Hac', transliteration: 'Al-Hajj', ayahCount: 78, revelationType: 'Medinan', revelationOrder: 103),
  SurahData(number: 23, nameArabic: 'المؤمنون', nameEnglish: 'The Believers', nameTurkish: 'Muminun', transliteration: 'Al-Mu\'minun', ayahCount: 118, revelationType: 'Meccan', revelationOrder: 74),
  SurahData(number: 24, nameArabic: 'النور', nameEnglish: 'The Light', nameTurkish: 'Nur', transliteration: 'An-Nur', ayahCount: 64, revelationType: 'Medinan', revelationOrder: 102),
  SurahData(number: 25, nameArabic: 'الفرقان', nameEnglish: 'The Criterion', nameTurkish: 'Furkan', transliteration: 'Al-Furqan', ayahCount: 77, revelationType: 'Meccan', revelationOrder: 42),
  SurahData(number: 26, nameArabic: 'الشعراء', nameEnglish: 'The Poets', nameTurkish: 'Suara', transliteration: 'Ash-Shu\'ara', ayahCount: 227, revelationType: 'Meccan', revelationOrder: 47),
  SurahData(number: 27, nameArabic: 'النمل', nameEnglish: 'The Ant', nameTurkish: 'Neml', transliteration: 'An-Naml', ayahCount: 93, revelationType: 'Meccan', revelationOrder: 48),
  SurahData(number: 28, nameArabic: 'القصص', nameEnglish: 'The Stories', nameTurkish: 'Kasas', transliteration: 'Al-Qasas', ayahCount: 88, revelationType: 'Meccan', revelationOrder: 49),
  SurahData(number: 29, nameArabic: 'العنكبوت', nameEnglish: 'The Spider', nameTurkish: 'Ankebut', transliteration: 'Al-Ankabut', ayahCount: 69, revelationType: 'Meccan', revelationOrder: 85),
  SurahData(number: 30, nameArabic: 'الروم', nameEnglish: 'The Romans', nameTurkish: 'Rum', transliteration: 'Ar-Rum', ayahCount: 60, revelationType: 'Meccan', revelationOrder: 84),
  SurahData(number: 31, nameArabic: 'لقمان', nameEnglish: 'Luqman', nameTurkish: 'Lokman', transliteration: 'Luqman', ayahCount: 34, revelationType: 'Meccan', revelationOrder: 57),
  SurahData(number: 32, nameArabic: 'السجدة', nameEnglish: 'The Prostration', nameTurkish: 'Secde', transliteration: 'As-Sajdah', ayahCount: 30, revelationType: 'Meccan', revelationOrder: 75),
  SurahData(number: 33, nameArabic: 'الأحزاب', nameEnglish: 'The Combined Forces', nameTurkish: 'Ahzab', transliteration: 'Al-Ahzab', ayahCount: 73, revelationType: 'Medinan', revelationOrder: 90),
  SurahData(number: 34, nameArabic: 'سبأ', nameEnglish: 'Sheba', nameTurkish: 'Sebe', transliteration: 'Saba', ayahCount: 54, revelationType: 'Meccan', revelationOrder: 58),
  SurahData(number: 35, nameArabic: 'فاطر', nameEnglish: 'The Originator', nameTurkish: 'Fatir', transliteration: 'Fatir', ayahCount: 45, revelationType: 'Meccan', revelationOrder: 43),
  SurahData(number: 36, nameArabic: 'يس', nameEnglish: 'Ya-Sin', nameTurkish: 'Yasin', transliteration: 'Ya-Sin', ayahCount: 83, revelationType: 'Meccan', revelationOrder: 41),
  SurahData(number: 37, nameArabic: 'الصافات', nameEnglish: 'Those Ranged in Ranks', nameTurkish: 'Saffat', transliteration: 'As-Saffat', ayahCount: 182, revelationType: 'Meccan', revelationOrder: 56),
  SurahData(number: 38, nameArabic: 'ص', nameEnglish: 'Sad', nameTurkish: 'Sad', transliteration: 'Sad', ayahCount: 88, revelationType: 'Meccan', revelationOrder: 38),
  SurahData(number: 39, nameArabic: 'الزمر', nameEnglish: 'The Troops', nameTurkish: 'Zumer', transliteration: 'Az-Zumar', ayahCount: 75, revelationType: 'Meccan', revelationOrder: 59),
  SurahData(number: 40, nameArabic: 'غافر', nameEnglish: 'The Forgiver', nameTurkish: 'Mumin', transliteration: 'Ghafir', ayahCount: 85, revelationType: 'Meccan', revelationOrder: 60),
  SurahData(number: 41, nameArabic: 'فصلت', nameEnglish: 'Explained in Detail', nameTurkish: 'Fussilet', transliteration: 'Fussilat', ayahCount: 54, revelationType: 'Meccan', revelationOrder: 61),
  SurahData(number: 42, nameArabic: 'الشورى', nameEnglish: 'The Consultation', nameTurkish: 'Sura', transliteration: 'Ash-Shura', ayahCount: 53, revelationType: 'Meccan', revelationOrder: 62),
  SurahData(number: 43, nameArabic: 'الزخرف', nameEnglish: 'The Ornaments of Gold', nameTurkish: 'Zuhruf', transliteration: 'Az-Zukhruf', ayahCount: 89, revelationType: 'Meccan', revelationOrder: 63),
  SurahData(number: 44, nameArabic: 'الدخان', nameEnglish: 'The Smoke', nameTurkish: 'Duhan', transliteration: 'Ad-Dukhan', ayahCount: 59, revelationType: 'Meccan', revelationOrder: 64),
  SurahData(number: 45, nameArabic: 'الجاثية', nameEnglish: 'The Crouching', nameTurkish: 'Casiye', transliteration: 'Al-Jathiyah', ayahCount: 37, revelationType: 'Meccan', revelationOrder: 65),
  SurahData(number: 46, nameArabic: 'الأحقاف', nameEnglish: 'The Wind-Curved Sandhills', nameTurkish: 'Ahkaf', transliteration: 'Al-Ahqaf', ayahCount: 35, revelationType: 'Meccan', revelationOrder: 66),
  SurahData(number: 47, nameArabic: 'محمد', nameEnglish: 'Muhammad', nameTurkish: 'Muhammed', transliteration: 'Muhammad', ayahCount: 38, revelationType: 'Medinan', revelationOrder: 95),
  SurahData(number: 48, nameArabic: 'الفتح', nameEnglish: 'The Victory', nameTurkish: 'Fetih', transliteration: 'Al-Fath', ayahCount: 29, revelationType: 'Medinan', revelationOrder: 111),
  SurahData(number: 49, nameArabic: 'الحجرات', nameEnglish: 'The Rooms', nameTurkish: 'Hucurat', transliteration: 'Al-Hujurat', ayahCount: 18, revelationType: 'Medinan', revelationOrder: 106),
  SurahData(number: 50, nameArabic: 'ق', nameEnglish: 'Qaf', nameTurkish: 'Kaf', transliteration: 'Qaf', ayahCount: 45, revelationType: 'Meccan', revelationOrder: 34),
  SurahData(number: 51, nameArabic: 'الذاريات', nameEnglish: 'The Winnowing Winds', nameTurkish: 'Zariyat', transliteration: 'Adh-Dhariyat', ayahCount: 60, revelationType: 'Meccan', revelationOrder: 67),
  SurahData(number: 52, nameArabic: 'الطور', nameEnglish: 'The Mount', nameTurkish: 'Tur', transliteration: 'At-Tur', ayahCount: 49, revelationType: 'Meccan', revelationOrder: 76),
  SurahData(number: 53, nameArabic: 'النجم', nameEnglish: 'The Star', nameTurkish: 'Necm', transliteration: 'An-Najm', ayahCount: 62, revelationType: 'Meccan', revelationOrder: 23),
  SurahData(number: 54, nameArabic: 'القمر', nameEnglish: 'The Moon', nameTurkish: 'Kamer', transliteration: 'Al-Qamar', ayahCount: 55, revelationType: 'Meccan', revelationOrder: 37),
  SurahData(number: 55, nameArabic: 'الرحمن', nameEnglish: 'The Most Merciful', nameTurkish: 'Rahman', transliteration: 'Ar-Rahman', ayahCount: 78, revelationType: 'Medinan', revelationOrder: 97),
  SurahData(number: 56, nameArabic: 'الواقعة', nameEnglish: 'The Inevitable', nameTurkish: 'Vakia', transliteration: 'Al-Waqi\'ah', ayahCount: 96, revelationType: 'Meccan', revelationOrder: 46),
  SurahData(number: 57, nameArabic: 'الحديد', nameEnglish: 'The Iron', nameTurkish: 'Hadid', transliteration: 'Al-Hadid', ayahCount: 29, revelationType: 'Medinan', revelationOrder: 94),
  SurahData(number: 58, nameArabic: 'المجادلة', nameEnglish: 'The Pleading Woman', nameTurkish: 'Mucadele', transliteration: 'Al-Mujadila', ayahCount: 22, revelationType: 'Medinan', revelationOrder: 105),
  SurahData(number: 59, nameArabic: 'الحشر', nameEnglish: 'The Exile', nameTurkish: 'Hasr', transliteration: 'Al-Hashr', ayahCount: 24, revelationType: 'Medinan', revelationOrder: 101),
  SurahData(number: 60, nameArabic: 'الممتحنة', nameEnglish: 'She That is Examined', nameTurkish: 'Mumtehine', transliteration: 'Al-Mumtahanah', ayahCount: 13, revelationType: 'Medinan', revelationOrder: 91),
  SurahData(number: 61, nameArabic: 'الصف', nameEnglish: 'The Ranks', nameTurkish: 'Saf', transliteration: 'As-Saf', ayahCount: 14, revelationType: 'Medinan', revelationOrder: 109),
  SurahData(number: 62, nameArabic: 'الجمعة', nameEnglish: 'Friday', nameTurkish: 'Cuma', transliteration: 'Al-Jumu\'ah', ayahCount: 11, revelationType: 'Medinan', revelationOrder: 110),
  SurahData(number: 63, nameArabic: 'المنافقون', nameEnglish: 'The Hypocrites', nameTurkish: 'Munafikun', transliteration: 'Al-Munafiqun', ayahCount: 11, revelationType: 'Medinan', revelationOrder: 104),
  SurahData(number: 64, nameArabic: 'التغابن', nameEnglish: 'The Mutual Disillusion', nameTurkish: 'Tegabun', transliteration: 'At-Taghabun', ayahCount: 18, revelationType: 'Medinan', revelationOrder: 108),
  SurahData(number: 65, nameArabic: 'الطلاق', nameEnglish: 'The Divorce', nameTurkish: 'Talak', transliteration: 'At-Talaq', ayahCount: 12, revelationType: 'Medinan', revelationOrder: 99),
  SurahData(number: 66, nameArabic: 'التحريم', nameEnglish: 'The Prohibition', nameTurkish: 'Tahrim', transliteration: 'At-Tahrim', ayahCount: 12, revelationType: 'Medinan', revelationOrder: 107),
  SurahData(number: 67, nameArabic: 'الملك', nameEnglish: 'The Sovereignty', nameTurkish: 'Mulk', transliteration: 'Al-Mulk', ayahCount: 30, revelationType: 'Meccan', revelationOrder: 77),
  SurahData(number: 68, nameArabic: 'القلم', nameEnglish: 'The Pen', nameTurkish: 'Kalem', transliteration: 'Al-Qalam', ayahCount: 52, revelationType: 'Meccan', revelationOrder: 2),
  SurahData(number: 69, nameArabic: 'الحاقة', nameEnglish: 'The Reality', nameTurkish: 'Hakka', transliteration: 'Al-Haqqah', ayahCount: 52, revelationType: 'Meccan', revelationOrder: 78),
  SurahData(number: 70, nameArabic: 'المعارج', nameEnglish: 'The Ascending Stairways', nameTurkish: 'Mearic', transliteration: 'Al-Ma\'arij', ayahCount: 44, revelationType: 'Meccan', revelationOrder: 79),
  SurahData(number: 71, nameArabic: 'نوح', nameEnglish: 'Noah', nameTurkish: 'Nuh', transliteration: 'Nuh', ayahCount: 28, revelationType: 'Meccan', revelationOrder: 71),
  SurahData(number: 72, nameArabic: 'الجن', nameEnglish: 'The Jinn', nameTurkish: 'Cin', transliteration: 'Al-Jinn', ayahCount: 28, revelationType: 'Meccan', revelationOrder: 40),
  SurahData(number: 73, nameArabic: 'المزمل', nameEnglish: 'The Enshrouded One', nameTurkish: 'Muzzemmil', transliteration: 'Al-Muzzammil', ayahCount: 20, revelationType: 'Meccan', revelationOrder: 3),
  SurahData(number: 74, nameArabic: 'المدثر', nameEnglish: 'The Cloaked One', nameTurkish: 'Muddessir', transliteration: 'Al-Muddaththir', ayahCount: 56, revelationType: 'Meccan', revelationOrder: 4),
  SurahData(number: 75, nameArabic: 'القيامة', nameEnglish: 'The Resurrection', nameTurkish: 'Kiyame', transliteration: 'Al-Qiyamah', ayahCount: 40, revelationType: 'Meccan', revelationOrder: 31),
  SurahData(number: 76, nameArabic: 'الإنسان', nameEnglish: 'The Human', nameTurkish: 'Insan', transliteration: 'Al-Insan', ayahCount: 31, revelationType: 'Medinan', revelationOrder: 98),
  SurahData(number: 77, nameArabic: 'المرسلات', nameEnglish: 'The Emissaries', nameTurkish: 'Murselat', transliteration: 'Al-Mursalat', ayahCount: 50, revelationType: 'Meccan', revelationOrder: 33),
  SurahData(number: 78, nameArabic: 'النبأ', nameEnglish: 'The Tidings', nameTurkish: 'Nebe', transliteration: 'An-Naba', ayahCount: 40, revelationType: 'Meccan', revelationOrder: 80),
  SurahData(number: 79, nameArabic: 'النازعات', nameEnglish: 'Those Who Drag Forth', nameTurkish: 'Naziat', transliteration: 'An-Nazi\'at', ayahCount: 46, revelationType: 'Meccan', revelationOrder: 81),
  SurahData(number: 80, nameArabic: 'عبس', nameEnglish: 'He Frowned', nameTurkish: 'Abese', transliteration: 'Abasa', ayahCount: 42, revelationType: 'Meccan', revelationOrder: 24),
  SurahData(number: 81, nameArabic: 'التكوير', nameEnglish: 'The Overthrowing', nameTurkish: 'Tekvir', transliteration: 'At-Takwir', ayahCount: 29, revelationType: 'Meccan', revelationOrder: 7),
  SurahData(number: 82, nameArabic: 'الانفطار', nameEnglish: 'The Cleaving', nameTurkish: 'Infitar', transliteration: 'Al-Infitar', ayahCount: 19, revelationType: 'Meccan', revelationOrder: 82),
  SurahData(number: 83, nameArabic: 'المطففين', nameEnglish: 'The Defrauding', nameTurkish: 'Mutaffifin', transliteration: 'Al-Mutaffifin', ayahCount: 36, revelationType: 'Meccan', revelationOrder: 86),
  SurahData(number: 84, nameArabic: 'الانشقاق', nameEnglish: 'The Sundering', nameTurkish: 'Insikak', transliteration: 'Al-Inshiqaq', ayahCount: 25, revelationType: 'Meccan', revelationOrder: 83),
  SurahData(number: 85, nameArabic: 'البروج', nameEnglish: 'The Mansions of the Stars', nameTurkish: 'Buruc', transliteration: 'Al-Buruj', ayahCount: 22, revelationType: 'Meccan', revelationOrder: 27),
  SurahData(number: 86, nameArabic: 'الطارق', nameEnglish: 'The Morning Star', nameTurkish: 'Tarik', transliteration: 'At-Tariq', ayahCount: 17, revelationType: 'Meccan', revelationOrder: 36),
  SurahData(number: 87, nameArabic: 'الأعلى', nameEnglish: 'The Most High', nameTurkish: 'Ala', transliteration: 'Al-A\'la', ayahCount: 19, revelationType: 'Meccan', revelationOrder: 8),
  SurahData(number: 88, nameArabic: 'الغاشية', nameEnglish: 'The Overwhelming', nameTurkish: 'Gasiye', transliteration: 'Al-Ghashiyah', ayahCount: 26, revelationType: 'Meccan', revelationOrder: 68),
  SurahData(number: 89, nameArabic: 'الفجر', nameEnglish: 'The Dawn', nameTurkish: 'Fecr', transliteration: 'Al-Fajr', ayahCount: 30, revelationType: 'Meccan', revelationOrder: 10),
  SurahData(number: 90, nameArabic: 'البلد', nameEnglish: 'The City', nameTurkish: 'Beled', transliteration: 'Al-Balad', ayahCount: 20, revelationType: 'Meccan', revelationOrder: 35),
  SurahData(number: 91, nameArabic: 'الشمس', nameEnglish: 'The Sun', nameTurkish: 'Sems', transliteration: 'Ash-Shams', ayahCount: 15, revelationType: 'Meccan', revelationOrder: 26),
  SurahData(number: 92, nameArabic: 'الليل', nameEnglish: 'The Night', nameTurkish: 'Leyl', transliteration: 'Al-Layl', ayahCount: 21, revelationType: 'Meccan', revelationOrder: 9),
  SurahData(number: 93, nameArabic: 'الضحى', nameEnglish: 'The Morning Hours', nameTurkish: 'Duha', transliteration: 'Ad-Duhaa', ayahCount: 11, revelationType: 'Meccan', revelationOrder: 11),
  SurahData(number: 94, nameArabic: 'الشرح', nameEnglish: 'The Relief', nameTurkish: 'Insirah', transliteration: 'Ash-Sharh', ayahCount: 8, revelationType: 'Meccan', revelationOrder: 12),
  SurahData(number: 95, nameArabic: 'التين', nameEnglish: 'The Fig', nameTurkish: 'Tin', transliteration: 'At-Tin', ayahCount: 8, revelationType: 'Meccan', revelationOrder: 28),
  SurahData(number: 96, nameArabic: 'العلق', nameEnglish: 'The Clot', nameTurkish: 'Alak', transliteration: 'Al-Alaq', ayahCount: 19, revelationType: 'Meccan', revelationOrder: 1),
  SurahData(number: 97, nameArabic: 'القدر', nameEnglish: 'The Power', nameTurkish: 'Kadir', transliteration: 'Al-Qadr', ayahCount: 5, revelationType: 'Meccan', revelationOrder: 25),
  SurahData(number: 98, nameArabic: 'البينة', nameEnglish: 'The Clear Proof', nameTurkish: 'Beyyine', transliteration: 'Al-Bayyinah', ayahCount: 8, revelationType: 'Medinan', revelationOrder: 100),
  SurahData(number: 99, nameArabic: 'الزلزلة', nameEnglish: 'The Earthquake', nameTurkish: 'Zilzal', transliteration: 'Az-Zalzalah', ayahCount: 8, revelationType: 'Medinan', revelationOrder: 93),
  SurahData(number: 100, nameArabic: 'العاديات', nameEnglish: 'The Courser', nameTurkish: 'Adiyat', transliteration: 'Al-Adiyat', ayahCount: 11, revelationType: 'Meccan', revelationOrder: 14),
  SurahData(number: 101, nameArabic: 'القارعة', nameEnglish: 'The Calamity', nameTurkish: 'Karia', transliteration: 'Al-Qari\'ah', ayahCount: 11, revelationType: 'Meccan', revelationOrder: 30),
  SurahData(number: 102, nameArabic: 'التكاثر', nameEnglish: 'The Rivalry in Worldly Increase', nameTurkish: 'Tekasur', transliteration: 'At-Takathur', ayahCount: 8, revelationType: 'Meccan', revelationOrder: 16),
  SurahData(number: 103, nameArabic: 'العصر', nameEnglish: 'The Declining Day', nameTurkish: 'Asr', transliteration: 'Al-Asr', ayahCount: 3, revelationType: 'Meccan', revelationOrder: 13),
  SurahData(number: 104, nameArabic: 'الهمزة', nameEnglish: 'The Traducer', nameTurkish: 'Humeze', transliteration: 'Al-Humazah', ayahCount: 9, revelationType: 'Meccan', revelationOrder: 32),
  SurahData(number: 105, nameArabic: 'الفيل', nameEnglish: 'The Elephant', nameTurkish: 'Fil', transliteration: 'Al-Fil', ayahCount: 5, revelationType: 'Meccan', revelationOrder: 19),
  SurahData(number: 106, nameArabic: 'قريش', nameEnglish: 'Quraysh', nameTurkish: 'Kureys', transliteration: 'Quraysh', ayahCount: 4, revelationType: 'Meccan', revelationOrder: 29),
  SurahData(number: 107, nameArabic: 'الماعون', nameEnglish: 'The Small Kindnesses', nameTurkish: 'Maun', transliteration: 'Al-Ma\'un', ayahCount: 7, revelationType: 'Meccan', revelationOrder: 17),
  SurahData(number: 108, nameArabic: 'الكوثر', nameEnglish: 'The Abundance', nameTurkish: 'Kevser', transliteration: 'Al-Kawthar', ayahCount: 3, revelationType: 'Meccan', revelationOrder: 15),
  SurahData(number: 109, nameArabic: 'الكافرون', nameEnglish: 'The Disbelievers', nameTurkish: 'Kafirun', transliteration: 'Al-Kafirun', ayahCount: 6, revelationType: 'Meccan', revelationOrder: 18),
  SurahData(number: 110, nameArabic: 'النصر', nameEnglish: 'The Divine Support', nameTurkish: 'Nasr', transliteration: 'An-Nasr', ayahCount: 3, revelationType: 'Medinan', revelationOrder: 114),
  SurahData(number: 111, nameArabic: 'المسد', nameEnglish: 'The Palm Fiber', nameTurkish: 'Tebbet', transliteration: 'Al-Masad', ayahCount: 5, revelationType: 'Meccan', revelationOrder: 6),
  SurahData(number: 112, nameArabic: 'الإخلاص', nameEnglish: 'The Sincerity', nameTurkish: 'Ihlas', transliteration: 'Al-Ikhlas', ayahCount: 4, revelationType: 'Meccan', revelationOrder: 22),
  SurahData(number: 113, nameArabic: 'الفلق', nameEnglish: 'The Daybreak', nameTurkish: 'Felak', transliteration: 'Al-Falaq', ayahCount: 5, revelationType: 'Meccan', revelationOrder: 20),
  SurahData(number: 114, nameArabic: 'الناس', nameEnglish: 'Mankind', nameTurkish: 'Nas', transliteration: 'An-Nas', ayahCount: 6, revelationType: 'Meccan', revelationOrder: 21),
];
